/**
 * The seam between the Python engine and this canvas.
 *
 * WHY THIS TEST EXISTS
 * --------------------
 * `learning-os` emits lessons; this package decides what a lesson is. Until
 * something produced by the first was fed to the second, "the engine emits
 * LessonInput" was a comment in a Python docstring — an assertion with nothing
 * behind it, in a codebase that has already been bitten three times by exactly
 * that shape.
 *
 * The fixture is generated by `python -m learning_os.api.cli` and committed. Each
 * side then tests its own half in its own language: the Python suite asserts the
 * emitter still produces those bytes, and this asserts the canvas still accepts
 * them. Neither mocks the other, and a divergence fails one of them loudly.
 *
 * WHY THE FIXTURE IS COMMITTED RATHER THAN GENERATED HERE
 * -------------------------------------------------------
 * Generating it in this job would need Python inside a Node workflow, and a
 * fixture regenerated on both sides can never disagree — which is precisely what
 * it exists to detect. Committed, it is a fact both jobs read.
 *
 * IF THIS FAILS
 * -------------
 * The engine and the canvas have diverged. Do not edit the fixture to make it
 * pass: it is the engine's output, not this package's input, and editing it here
 * hides the divergence rather than resolving it. Read the issues, decide which
 * side is wrong, and fix that side.
 *
 * WHY THE TEACHING LEVEL HERE IS `'answer'`
 * -----------------------------------------
 * When the teaching rules landed, every fixture below was refused: no opening
 * definition, no closing summary, nothing marked. Following the instruction
 * above, the question was which side is wrong — and the answer taken is that
 * the CANVAS was asking for the wrong thing, not that the engine emits bad
 * output. These fixtures are a `worked_example` and two learner attempts. They
 * are replies, not lessons with a beginning and an end, and the engine has no
 * builder that could give them one: `emit` produces `{id, kind, emphasis,
 * body}` and refuses every kind that is not `prose` or `callout`.
 *
 * SAID PLAINLY, BECAUSE IT IS A DECISION AND NOT A DISCOVERY: this settles by
 * fiat that the engine never emits a full taught lesson. Nothing in the Python
 * side enforces that today. If the engine ever should emit one, the honest fix
 * is the Python emitter — teaching-shaped output, then regenerated fixtures —
 * and this level goes back to `'lesson'`. It is NOT to relax the canvas.
 *
 * The fixtures themselves are untouched, which is the part the note above
 * actually protects.
 */

import { describe, expect, it } from 'vitest'

import learnerA from '../lessons/generated/learner-a-first-attempt.json'
import learnerB from '../lessons/generated/learner-b-preferred-mechanism-failed.json'
import { deriveBeats } from '../teach/beats'
import { checkBeats } from '../teach/contract'

import engineLesson from './__fixtures__/engine-lesson.json'
import { validateLesson } from './validate'

/**
 * EVERY committed engine lesson, not just the one fixture.
 *
 * The single-fixture version of this file passed while the canvas was importing
 * a lesson it would refuse to render. `engine-lesson.json` is emitted under
 * WORKED_EXAMPLE, whose blocks are all prose — so the only shape it ever
 * exercised was the one that worked. The emitter built `table` the same way it
 * built `prose`, as `{id, kind, emphasis, body}`, and Zod rejected it with
 * `Unrecognized key(s) in object: 'body'` the moment a different strategy was
 * selected.
 *
 * One fixture tests one strategy. Listing every lesson the app imports is what
 * makes this test about the SEAM rather than about one lucky path through it.
 */
const EMITTED = [
  ['engine-lesson (worked_example)', engineLesson],
  ['learner-a (first attempt)', learnerA],
  ['learner-b (fallback strategy)', learnerB],
] as const

describe.each(EMITTED)('%s', (_name, lesson) => {
  it('is accepted by the canvas validator', () => {
    const result = validateLesson(lesson, { teaching: 'answer' })
    if (!result.ok) console.error(JSON.stringify(result.issues, null, 2))
    expect(result.ok).toBe(true)
  })

  it('carries a block shape the schema actually defines', () => {
    /* The specific defect: a kind the canvas KNOWS, carrying the wrong fields.
       `validateLesson` catches it, but a bare `ok === false` above does not say
       which block or which key — and that message is the difference between a
       five-minute fix and an afternoon. */
    const result = validateLesson(lesson, { teaching: 'answer' })
    /* `Result` is a discriminated union — `issues` exists only on the failing
       arm. Narrowing rather than reaching for `.issues` keeps the union doing
       its job, which is refusing to let a caller read a field that is not
       there on the branch they are on. */
    const unrecognised = result.ok
      ? []
      : result.issues.filter((i) => i.message.includes('Unrecognized key'))
    expect(unrecognised, JSON.stringify(unrecognised, null, 2)).toEqual([])
  })
})

describe('a lesson emitted by the engine', () => {
  it('is accepted by the canvas validator', () => {
    const result = validateLesson(engineLesson, { teaching: 'answer' })

    /* Printed rather than swallowed: a bare `false` tells whoever broke this
       nothing about which field the two languages disagree on. */
    if (!result.ok) {
      console.error(JSON.stringify(result.issues, null, 2))
    }

    expect(result.ok).toBe(true)
  })

  it('can be taught one beat at a time', () => {
    /* Validating is not enough. A lesson can parse and still collapse into one
       twelve-block beat — a lecture, which is the exact failure the beat system
       exists to prevent. The engine sets `emphasis` and emits `relations`
       deliberately for this reason, so this asserts that intent survived the
       crossing. */
    const result = validateLesson(engineLesson, { teaching: 'answer' })
    expect(result.ok).toBe(true)
    if (!result.ok) return

    const beats = deriveBeats(result.lesson)
    expect(beats.length).toBeGreaterThan(0)
    /* Structural beat rules only, matching `'answer'` above: the partition must
       be exact and no beat may count steps at the learner. "Every beat shows
       something" is not asserted, because `emit` can only build `prose` and
       `callout` — the engine cannot produce a representation at all, so the
       rule could never pass and would never point at a real fault. */
    expect(checkBeats(beats, result.lesson, { teaching: false })).toEqual([])
  })

  it('carries every block into some beat, losing none', () => {
    const result = validateLesson(engineLesson, { teaching: 'answer' })
    expect(result.ok).toBe(true)
    if (!result.ok) return

    const inBeats = deriveBeats(result.lesson).flatMap((beat) => [...beat.blockIds])
    expect([...inBeats].sort()).toEqual(result.lesson.blocks.map((b) => b.id).sort())
  })

  it('states no geometry, style, or step count', () => {
    /* Laws 2 and 3, asserted on the SERIALISED bytes rather than the parsed
       object. Checking parsed fields proves only that the fields this version
       has are clean; checking the text catches one added later inside a nested
       block, which is where it would actually appear. */
    const raw = JSON.stringify(engineLesson)
    for (const banned of [
      '"x"', '"y"', '"width"', '"height"', '"top"', '"left"',
      '"color"', '"colour"', '"fontSize"', '"padding"', '"margin"', '"radius"',
      '"beat"', '"beats"', '"step"', '"steps"', '"total"', '"index"',
    ]) {
      expect(raw, `${banned} reached the payload`).not.toContain(banned)
    }
  })
})
