/**
 * The seam between the Python engine and this canvas.
 *
 * WHY THIS TEST EXISTS
 * --------------------
 * `learning-os` emits lessons; this package decides what a lesson is. Until
 * something produced by the first was fed to the second, "the engine emits
 * LessonInput" was a comment in a Python docstring — an assertion with nothing
 * behind it, in a codebase that has already been bitten three times by exactly
 * that shape.
 *
 * The fixture is generated by `python -m learning_os.api.cli` and committed. Each
 * side then tests its own half in its own language: the Python suite asserts the
 * emitter still produces those bytes, and this asserts the canvas still accepts
 * them. Neither mocks the other, and a divergence fails one of them loudly.
 *
 * WHY THE FIXTURE IS COMMITTED RATHER THAN GENERATED HERE
 * -------------------------------------------------------
 * Generating it in this job would need Python inside a Node workflow, and a
 * fixture regenerated on both sides can never disagree — which is precisely what
 * it exists to detect. Committed, it is a fact both jobs read.
 *
 * IF THIS FAILS
 * -------------
 * The engine and the canvas have diverged. Do not edit the fixture to make it
 * pass: it is the engine's output, not this package's input, and editing it here
 * hides the divergence rather than resolving it. Read the issues, decide which
 * side is wrong, and fix that side.
 */

import { describe, expect, it } from 'vitest'

import { deriveBeats } from '../teach/beats'
import { checkBeats } from '../teach/contract'

import engineLesson from './__fixtures__/engine-lesson.json'
import { validateLesson } from './validate'

describe('a lesson emitted by the engine', () => {
  it('is accepted by the canvas validator', () => {
    const result = validateLesson(engineLesson)

    /* Printed rather than swallowed: a bare `false` tells whoever broke this
       nothing about which field the two languages disagree on. */
    if (!result.ok) {
      console.error(JSON.stringify(result.issues, null, 2))
    }

    expect(result.ok).toBe(true)
  })

  it('can be taught one beat at a time', () => {
    /* Validating is not enough. A lesson can parse and still collapse into one
       twelve-block beat — a lecture, which is the exact failure the beat system
       exists to prevent. The engine sets `emphasis` and emits `relations`
       deliberately for this reason, so this asserts that intent survived the
       crossing. */
    const result = validateLesson(engineLesson)
    expect(result.ok).toBe(true)
    if (!result.ok) return

    const beats = deriveBeats(result.lesson)
    expect(beats.length).toBeGreaterThan(0)
    expect(checkBeats(beats, result.lesson)).toEqual([])
  })

  it('carries every block into some beat, losing none', () => {
    const result = validateLesson(engineLesson)
    expect(result.ok).toBe(true)
    if (!result.ok) return

    const inBeats = deriveBeats(result.lesson).flatMap((beat) => [...beat.blockIds])
    expect([...inBeats].sort()).toEqual(result.lesson.blocks.map((b) => b.id).sort())
  })

  it('states no geometry, style, or step count', () => {
    /* Laws 2 and 3, asserted on the SERIALISED bytes rather than the parsed
       object. Checking parsed fields proves only that the fields this version
       has are clean; checking the text catches one added later inside a nested
       block, which is where it would actually appear. */
    const raw = JSON.stringify(engineLesson)
    for (const banned of [
      '"x"', '"y"', '"width"', '"height"', '"top"', '"left"',
      '"color"', '"colour"', '"fontSize"', '"padding"', '"margin"', '"radius"',
      '"beat"', '"beats"', '"step"', '"steps"', '"total"', '"index"',
    ]) {
      expect(raw, `${banned} reached the payload`).not.toContain(banned)
    }
  })
})
