#!/usr/bin/env node
/* Generate src/data/exams/<exam>.ts from the official syllabus PDFs.
 *
 * Re-runnable: point it at a re-fetched PDF and the data regenerates. Nothing
 * here is hand-typed, so a mistake is a code bug a test catches rather than a
 * wrong fact a student revises from.
 */
import { execFileSync } from 'node:child_process'
import { mkdirSync, writeFileSync, readFileSync, existsSync } from 'node:fs'
import { createHash } from 'node:crypto'
import { resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

import { EXAM_SOURCES, parseExam } from './exams.mjs'

const REPO = fileURLToPath(new URL('../../..', import.meta.url))
const PDF_DIR = resolve(REPO, 'data/source-pdfs/exams')
const OUT_DIR = resolve(REPO, 'frontend/src/data/exams')

export function toModule(exam, source) {
  const units = exam.subjects.flatMap((s) => s.units)
  return `// GENERATED by scripts/curriculum/build-exams.mjs — do not edit by hand.
//
// Source:     ${source.url}
// Discovered: ${source.discoveredFrom}  (link text: "${source.linkText}")
// sha256:     ${source.sha256}
//
// Every unit carries the page it was read from. A claim that cannot name its
// page is a claim nobody can check.
import type { ExamSyllabus } from '../../types'

export const ${exam.examId.replace(/[^a-z0-9]/gi, '_')}: ExamSyllabus = ${JSON.stringify(
    { id: exam.examId, source, subjects: exam.subjects },
    null,
    2,
  )} as const

export const unitCount = ${units.length}
`
}

function main() {
  mkdirSync(OUT_DIR, { recursive: true })
  const built = []
  for (const [id, source] of Object.entries(EXAM_SOURCES)) {
    const pdf = resolve(PDF_DIR, `${id}.pdf`)
    if (!existsSync(pdf)) {
      // Not silent, and not fatal: a missing local PDF is a fetch problem, and
      // pretending the exam has no units would ship an empty syllabus.
      console.error(`MISSING ${pdf} — run curriculum:fetch-exams first`)
      process.exitCode = 1
      continue
    }
    const digest = createHash('sha256').update(readFileSync(pdf)).digest('hex')
    if (digest !== source.sha256) {
      console.error(`DIGEST CHANGED for ${id}\n  locked  ${source.sha256}\n  on disk ${digest}`)
      console.error('  The syllabus was revised. Review it, then update EXAM_SOURCES.')
      process.exitCode = 1
      continue
    }
    const text = execFileSync('pdftotext', ['-layout', pdf, '-'], {
      encoding: 'utf8', maxBuffer: 64 * 1024 * 1024,
    })
    const exam = parseExam(id, text)
    writeFileSync(resolve(OUT_DIR, `${id}.ts`), toModule(exam, source))
    const n = exam.subjects.reduce((a, s) => a + s.units.length, 0)
    built.push(`  ${id}: ${n} units across ${exam.subjects.length} subjects`)
  }
  if (built.length) console.log('exams built:\n' + built.join('\n'))
}

// Compared as resolved PATHS, not as a URL string. This repository's checkout
// path contains a space, which `file://` percent-encodes -- so the string form
// silently never matches and the script exits having done nothing.
if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) main()
