"""initial schema

Revision ID: 0001_initial
Revises: 
Create Date: 2026-08-25 11:30:27.373339
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '0001_initial'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('concepts',
    sa.Column('id', sa.String(length=120), nullable=False),
    sa.Column('subject', sa.String(length=64), nullable=False),
    sa.Column('chapter', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('learners',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cohort', sa.String(length=64), nullable=False),
    sa.Column('stream', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skills',
    sa.Column('id', sa.String(length=120), nullable=False),
    sa.Column('concept_id', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attempts',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('learner_id', sa.String(length=64), nullable=False),
    sa.Column('skill_id', sa.String(length=120), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('correct', sa.Boolean(), nullable=False),
    sa.Column('difficulty', sa.Float(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.CheckConstraint(
        'difficulty >= 0.0 AND difficulty <= 1.0',
        name='ck_attempts_difficulty_range',
    ),
    sa.ForeignKeyConstraint(['learner_id'], ['learners.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('learner_id', 'idempotency_key', name='uq_attempts_learner_idempotency')
    )
    op.create_table('mastery',
    sa.Column('learner_id', sa.String(length=64), nullable=False),
    sa.Column('skill_id', sa.String(length=120), nullable=False),
    sa.Column('level', sa.Float(), nullable=False),
    sa.Column('last_review_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('next_review_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('level >= 0.0 AND level <= 1.0', name='ck_mastery_level_range'),
    sa.CheckConstraint('next_review_at >= last_review_at', name='ck_mastery_review_order'),
    sa.ForeignKeyConstraint(['learner_id'], ['learners.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('learner_id', 'skill_id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('learner_id', sa.String(length=64), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('objective', sa.String(length=400), nullable=False),
    sa.Column('skill_id', sa.String(length=120), nullable=True),
    sa.CheckConstraint(
        'closed_at IS NULL OR closed_at >= opened_at',
        name='ck_sessions_close_after_open',
    ),
    sa.ForeignKeyConstraint(['learner_id'], ['learners.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sessions')
    op.drop_table('mastery')
    op.drop_table('attempts')
    op.drop_table('skills')
    op.drop_table('learners')
    op.drop_table('concepts')
    # ### end Alembic commands ###
