// GENERATED by scripts/curriculum/build-exams.mjs — do not edit by hand.
//
// Source:     https://consortiumofnlus.ac.in/clat-2027/ug-syllabus.html
// Discovered: https://consortiumofnlus.ac.in/clat-2027/  (link text: "Syllabus & Guide")
// sha256:     e5a90081d2137504024f0155dd59c71c9d5be4f24342215d72dfdf5c84e1fd70
//
// The Consortium site is a JavaScript application: this link is present only in the RENDERED page, not in the HTML a plain fetch returns. Re-fetch it by reading the rendered page, never by constructing the path.
import type { ExamSkillPaper } from '../../types'

export const clat_2027: ExamSkillPaper = {
  "id": "clat-2027",
  "source": {
    "url": "https://consortiumofnlus.ac.in/clat-2027/ug-syllabus.html",
    "discoveredFrom": "https://consortiumofnlus.ac.in/clat-2027/",
    "linkText": "Syllabus & Guide",
    "sha256": "e5a90081d2137504024f0155dd59c71c9d5be4f24342215d72dfdf5c84e1fd70",
    "note": "The Consortium site is a JavaScript application: this link is present only in the RENDERED page, not in the HTML a plain fetch returns. Re-fetch it by reading the rendered page, never by constructing the path."
  },
  "questions": 120,
  "minutes": 120,
  "negativeMarking": 0.25,
  "sections": [
    {
      "id": "english-language",
      "name": "English Language",
      "description": "In this section of the UG-CLAT 2027, you will be provided passages of about 450 words each. These passages will be derived from contemporary or historically significant fiction and non-fiction writing, and would be of a standard that a 12th standard student may be able to read in about 5-7 minutes. Each passage will be followed by a series of questions that will require you to demonstrate your comprehension and language skills, including your abilities to:",
      "skills": [
        "Read and comprehend the main point discussed in the passage, as well as any arguments and viewpoints discussed or set out in the passage",
        "Draw inferences and conclusions based on the passage",
        "Summarise the passage",
        "Compare and contrast the different arguments or viewpoints set out in the passage; and",
        "Understand the meaning of various words and phrases in the context that they are used in the passage"
      ],
      "passageWords": 450
    },
    {
      "id": "current-affairs-general-knowledge",
      "name": "Current Affairs Including General Knowledge",
      "description": "In this section, you will be provided passages of up to 450 words each. The passages will be derived from news, journalistic sources and other non-fiction writing. The questions may include an examination of legal information or knowledge discussed in or related to the passage, but would not require any additional knowledge of the law beyond the passage. Each passage will be followed by a series of questions that will require you to demonstrate your awareness of various aspects of current affairs and general knowledge, including:",
      "skills": [
        "Contemporary events of significance from India and the world",
        "Arts and culture",
        "International affairs; and",
        "Historical events of continuing significance"
      ],
      "passageWords": 450
    },
    {
      "id": "legal-reasoning",
      "name": "Legal Reasoning",
      "description": "In this section, you will be expected to read passages of around 450 words each. The passages may relate to fact situations or scenarios involving legal matters, public policy questions or moral philosophical enquiries. You will not require any prior knowledge of law to attempt the questions in this section. You will benefit from a general awareness of contemporary legal and moral issues to better apply general principles or propositions to the given fact scenarios. Each passage would be followed by a series of questions that will require you to:",
      "skills": [
        "Identify and infer the rules and principles set out in the passage",
        "Apply such rules and principles to various fact situations; and",
        "Understand how changes to the rules or principles may alter their application to various fact situations"
      ],
      "passageWords": 450
    },
    {
      "id": "logical-reasoning",
      "name": "Logical Reasoning",
      "description": "The Logical Reasoning section of the UG-CLAT 2027 will include a series of short passages of about 450 words each. Each passage will be followed by one or more questions that will require you to:",
      "skills": [
        "Recognise an argument, its premises and conclusions",
        "Read and identify the arguments set out in the passage",
        "Critically analyse patterns of reasoning, and assess how conclusions may depend on particular premises or evidence, and how conclusions may be strengthened or weakened as a consequence of an alteration in premises or supporting facts",
        "Infer what follows from the passage and apply these inferences to new situations",
        "Draw relationships and analogies, identify contradictions and equivalence, and assess the effectiveness of arguments"
      ],
      "passageWords": 450
    },
    {
      "id": "quantitative-techniques",
      "name": "Quantitative Techniques",
      "description": "The Quantitative Techniques section of the UG-CLAT 2027 will include short sets of facts or propositions, or other textual representations of numerical information, followed by a series of questions. You will be required to derive information from the passages or questions, and apply mathematical operations on such information. The questions will require you to:",
      "skills": [
        "Derive, infer, and manipulate numerical information set out in such passages; and",
        "Apply various 10th standard mathematical operations on such information, including from areas such as ratios and proportions, basic algebra, mensuration and statistical estimation"
      ],
      "passageWords": null
    }
  ]
} as const
