// GENERATED by scripts/curriculum/build-exams.mjs — do not edit by hand.
//
// Source:     https://www.iimrohtak.ac.in/panel/assets/IPM%2008_FAQ_2026.pdf
// Discovered: https://www.iimrohtak.ac.in/ipm.php  (link text: "IPM 08_FAQ_2026.pdf")
// sha256:     688b4e81d0fbf03f1c926eecf31bc41206877c1975470178fb7673bfea15e7ae
//
// The test pattern is in the admissions FAQ, not on the programme page. Do NOT use "IPMAT 2026 Summary.pdf" from the same page: that file is candidate statistics, not a syllabus.
import type { ExamPatternPaper } from '../../types'

export const ipmat_2026_rohtak: ExamPatternPaper = {
  "institute": "IIM Rohtak",
  "covers": "The IPM Aptitude Test set by IIM Rohtak.",
  "notCovered": "IIM Indore runs a separate IPMAT with a different structure. It is not described here, and its site did not answer when this was built.",
  "sections": [
    {
      "id": "quantitative-ability",
      "name": "Quantitative Ability",
      "questions": 40
    },
    {
      "id": "logical-reasoning",
      "name": "Logical Reasoning",
      "questions": 40
    },
    {
      "id": "verbal-ability",
      "name": "Verbal Ability",
      "questions": 40
    }
  ],
  "questions": 120,
  "minutes": 120,
  "marksPerQuestion": 4,
  "negativeMarking": 1,
  "optional": {
    "name": "Legal Reasoning",
    "questions": 20,
    "minutes": 20,
    "appliesWhen": "the candidate also chose the Integrated Programme in Law (IPL)"
  },
  "id": "ipmat-2026-rohtak",
  "source": {
    "url": "https://www.iimrohtak.ac.in/panel/assets/IPM%2008_FAQ_2026.pdf",
    "discoveredFrom": "https://www.iimrohtak.ac.in/ipm.php",
    "linkText": "IPM 08_FAQ_2026.pdf",
    "sha256": "688b4e81d0fbf03f1c926eecf31bc41206877c1975470178fb7673bfea15e7ae",
    "note": "The test pattern is in the admissions FAQ, not on the programme page. Do NOT use \"IPMAT 2026 Summary.pdf\" from the same page: that file is candidate statistics, not a syllabus."
  }
} as const
