// GENERATED by scripts/curriculum/build-exams.mjs — do not edit by hand.
//
// Source:     https://cdnbbsr.s3waas.gov.in/s3f8e59f4b2fe7c5705bf878bbd494ccdf/uploads/2025/10/202510311323551056.pdf
// Discovered: https://jeemain.nta.nic.in/  (link text: "Syllabus")
// sha256:     7cad9da2a12065444828f744bd9f1a93a2dd0d9bd54c32a6d92d94a769e4f905
//
// Every unit carries the page it was read from. A claim that cannot name its
// page is a claim nobody can check.
import type { ExamSyllabus } from '../../types'

export const jee_main_2026: ExamSyllabus = {
  "id": "jee-main-2026",
  "source": {
    "url": "https://cdnbbsr.s3waas.gov.in/s3f8e59f4b2fe7c5705bf878bbd494ccdf/uploads/2025/10/202510311323551056.pdf",
    "discoveredFrom": "https://jeemain.nta.nic.in/",
    "linkText": "Syllabus",
    "sha256": "7cad9da2a12065444828f744bd9f1a93a2dd0d9bd54c32a6d92d94a769e4f905"
  },
  "subjects": [
    {
      "id": "mathematics",
      "units": [
        {
          "number": 1,
          "title": "SETS, RELATIONS AND FUNCTIONS",
          "topics": [
            "Sets and their representation",
            "Union, intersection and complement of sets and their algebraic properties",
            "Power set",
            "Relations, type of relations, equivalence relations, functions",
            "one-one, into and onto functions, the composition of functions"
          ],
          "source": {
            "pdf": "jee-main-2026.pdf",
            "page": 1
          }
        },
        {
          "number": 2,
          "title": "COMPLEX NUMBERS AND QUADRATIC EQUATIONS",
          "topics": [
            "Relations between roots and coefficients, nature of roots, the formation of quadratic equations with given roots"
          ],
          "source": {
            "pdf": "jee-main-2026.pdf",
            "page": 1
          }
        },
        {
          "number": 3,
          "title": "MATRICES AND DETERMINANTS",
          "topics": [
            "Matrices, algebra of matrices, type of matrices, determinants and matrices of order two and three, evaluation of determinants, area of triangles using determinants",
            "Adjoint and inverse of a square matrix",
            "Test of consistency and solution of simultaneous linear equations in two or three variables using matrices"
          ],
          "source": {
            "pdf": "jee-main-2026.pdf",
            "page": 1
          }
        },
        {
          "number": 4,
          "title": "PERMUTATIONS AND COMBINATIONS",
          "topics": [
            "The fundamental principle of counting, permutations and combinations",
            "Meaning of P(n, r) and C(n, r)",
            "Simple applications"
          ],
          "source": {
            "pdf": "jee-main-2026.pdf",
            "page": 1
          }
        },
        {
          "number": 5,
          "title": "BINOMIAL THEOREM AND ITS SIMPLE APPLICATIONS",
          "topics": [
            "Binomial theorem for a positive integral index, general term and middle term and simple applications"
          ],
          "source": {
            "pdf": "jee-main-2026.pdf",
            "page": 1
          }
        },
        {
          "number": 6,
          "title": "SEQUENCE AND SERIES",
          "topics": [
            "Arithmetic and Geometric progressions, insertion of arithmetic, geometric means between two given numbers, Relation between A.M and G.M"
          ],
          "source": {
            "pdf": "jee-main-2026.pdf",
            "page": 1
          }
        },
        {
          "number": 7,
          "title": "LIMIT, CONTINUITY AND DIFFERENTIABILITY",
          "topics": [
            "Real–valued functions, algebra of functions",
            "polynomial, rational, trigonometric, logarithmic and exponential functions",
            "inverse functions",
            "Graphs of simple functions",
            "Limits, continuity and differentiability",
            "Differentiation of the sum, difference, product and quotient of two functions",
            "Differentiation of trigonometric, inverse trigonometric, logarithmic, exponential, composite and implicit functions",
            "derivatives of order upto two, Applications of derivatives: Rate of change of quantities, monotonic-Increasing and decreasing functions, Maxima and minima of functions of one variable"
          ],
          "source": {
            "pdf": "jee-main-2026.pdf",
            "page": 1
          }
        },
        {
          "number": 8,
          "title": "INTEGRAL CALCULAS",
          "topics": [
            "Integral as an anti-derivative, Fundamental integrals involving algebraic, trigonometric, exponential and logarithmic functions",
            "Integration by substitution, by parts and by partial fractions",
            "Integration using trigonometric identities",
            "Evaluation of simple integrals of the type The fundamental theorem of calculus, properties of definite integrals",
            "Evaluation of definite integrals, determining areas of the regions bounded by simple curves by simple curves in standard forms"
          ],
          "source": {
            "pdf": "jee-main-2026.pdf",
            "page": 1
          }
        },
        {
          "number": 9,
          "title": "DIFFRENTIAL EQUATIONS",
          "topics": [],
          "source": {
            "pdf": "jee-main-2026.pdf",
            "page": 2
          }
        },
        {
          "number": 10,
          "title": "CO-ORDINATE GEOMETRY",
          "topics": [],
          "source": {
            "pdf": "jee-main-2026.pdf",
            "page": 2
          }
        },
        {
          "number": 11,
          "title": "THREE DIMENSIONAL GEOMETRY",
          "topics": [
            "Coordinates of a point in space, the distance between two points, section formula, direction ratios and direction cosines and the angle between two intersecting lines",
            "Equation of a line",
            "Skew lines, the shortest distance between them and its equation"
          ],
          "source": {
            "pdf": "jee-main-2026.pdf",
            "page": 2
          }
        },
        {
          "number": 12,
          "title": "VECTOR ALGEBRA",
          "topics": [
            "Vectors and scalars, the addition of vectors, components of a vector in two dimensions and three-dimensional spaces, scalar and vector products"
          ],
          "source": {
            "pdf": "jee-main-2026.pdf",
            "page": 2
          }
        },
        {
          "number": 13,
          "title": "STATISTICS AND PROBABILITY",
          "topics": [
            "Measures of dispersion",
            "calculation of mean, median, mode of grouped and ungrouped data, calculation of standard deviation, variance and mean deviation for grouped and ungrouped data",
            "Probability: Probability of an event, addition and multiplication theorems of probability, Baye's theorem, probability distribution of a random variable"
          ],
          "source": {
            "pdf": "jee-main-2026.pdf",
            "page": 2
          }
        },
        {
          "number": 14,
          "title": "TRIGONOMETRY",
          "topics": [
            "Trigonometrical identities and trigonometrical functions, inverse trigonometrical functions their properties",
            "Syllabus for JEE (Main) - 2026 PHYSICS"
          ],
          "source": {
            "pdf": "jee-main-2026.pdf",
            "page": 2
          }
        }
      ]
    },
    {
      "id": "physics",
      "units": [
        {
          "number": 1,
          "title": "Units and Measurements",
          "topics": [
            "Units of measurements, System of units, SI Units, fundamental and derived units, least count, significant figures, Errors in measurements",
            "Dimensions of Physics quantities, dimensional analysis and its applications"
          ],
          "source": {
            "pdf": "jee-main-2026.pdf",
            "page": 3
          }
        },
        {
          "number": 2,
          "title": "Kinematics",
          "topics": [
            "Motion in a plane, projectile motion, uniform circular motion"
          ],
          "source": {
            "pdf": "jee-main-2026.pdf",
            "page": 3
          }
        },
        {
          "number": 3,
          "title": "Laws of Motion",
          "topics": [
            "Force and inertia, Newton’s first law of motion, momentum, Newton’s second Law of motion, impulse, Newton’s third Law of motion",
            "Law of conservation of linear momentum and its applications, equilibrium of concurrent forces",
            "Static and Kinetic friction, laws of friction, rolling friction",
            "Dynamics of uniform circular motion, centripetal force and its applications: vehicle on a level circular road, vehicle on a banked road"
          ],
          "source": {
            "pdf": "jee-main-2026.pdf",
            "page": 3
          }
        },
        {
          "number": 4,
          "title": "Work, Energy and Power",
          "topics": [
            "Work done by a constant force and a variable force, kinetic and potential energies, work-energy theorem, power",
            "The potential energy of a spring, conservation of mechanical energy, conservative and non- conservative forces, motion in a vertical circle",
            "Elastic and inelastic collisions in one and two dimensions"
          ],
          "source": {
            "pdf": "jee-main-2026.pdf",
            "page": 3
          }
        },
        {
          "number": 5,
          "title": "Rotational Motion",
          "topics": [
            "Centre of mass of a two-particle system, centre of mass of a rigid body",
            "Basic concepts of rotational motion, moment of a force, torque, angular momentum, conservation of angular momentum and its applications",
            "The moment of inertia, the radius of gyration, values of moments of inertia for simple geometrical objects, parallel and perpendicular axes theorems and their applications",
            "Equilibrium of rigid bodies, rigid body rotation and equations of rotational motion, comparison of linear and rotational motions"
          ],
          "source": {
            "pdf": "jee-main-2026.pdf",
            "page": 3
          }
        },
        {
          "number": 6,
          "title": "Gravitation",
          "topics": [
            "The universal law of gravitation",
            "Acceleration due to gravity and its variation with altitude and depth",
            "Kepler’s law of planetary motion",
            "Gravitational potential energy, gravitational potential",
            "Escape velocity, motion of a satellite, orbital velocity, time period and energy of satellite"
          ],
          "source": {
            "pdf": "jee-main-2026.pdf",
            "page": 3
          }
        },
        {
          "number": 7,
          "title": "Properties of Solids and Liquids",
          "topics": [
            "Elastic behaviour, stress-strain relationship, Hooke's Law, Young's modulus, bulk modulus and modulus of rigidity",
            "Surface energy and surface tension, angle of contact, excess of pressure across a curved surface, application of surface tension: drops, bubbles and capillary rise",
            "Heat, temperature, thermal expansion, specific heat capacity, calorimetry, change of state, latent heat",
            "Heat transfer: conduction, convection and radiation"
          ],
          "source": {
            "pdf": "jee-main-2026.pdf",
            "page": 3
          }
        },
        {
          "number": 8,
          "title": "Thermodynamics",
          "topics": [
            "Thermal equilibrium and the concept of temperature, zeroth law of thermodynamics, heat, work and internal energy",
            "The first law of thermodynamics, isothermal and adiabatic processes",
            "The second law of thermodynamics: reversible and irreversible processes"
          ],
          "source": {
            "pdf": "jee-main-2026.pdf",
            "page": 4
          }
        },
        {
          "number": 9,
          "title": "Kinetic Theory of Gases",
          "topics": [],
          "source": {
            "pdf": "jee-main-2026.pdf",
            "page": 4
          }
        },
        {
          "number": 10,
          "title": "Oscillations and Waves",
          "topics": [
            "Oscillations and periodic motion: time period, frequency, displacement as a function of time, periodic functions"
          ],
          "source": {
            "pdf": "jee-main-2026.pdf",
            "page": 4
          }
        },
        {
          "number": 11,
          "title": "Electrostatics",
          "topics": [
            "Electric charges: conservation of charge, Coulomb's law forces between two point charges, forces between multiple charges, superposition principle and continuous charge distribution",
            "Electric field: electric field due to a point charge, electric field lines, electric dipole, electric field due to a dipole, torque on a dipole in a uniform electric field",
            "Electric flux, Gauss's law and its applications to find field due to infinitely long uniformly charged straight wire, uniformly charged infinite plane sheet and uniformly charged thin spherical shell"
          ],
          "source": {
            "pdf": "jee-main-2026.pdf",
            "page": 4
          }
        },
        {
          "number": 12,
          "title": "Current Electricity",
          "topics": [
            "Internal resistance, potential difference and emf of a cell, a combination of cells in series and parallel",
            "Kirchhoff’s laws and their applications, Wheatstone bridge, Metre Bridge"
          ],
          "source": {
            "pdf": "jee-main-2026.pdf",
            "page": 5
          }
        },
        {
          "number": 13,
          "title": "Magnetic Effects of Current and Magnetism",
          "topics": [
            "Biot - Savart law and its application to the current carrying circular loop, Ampere's law and its applications to infinitely long current carrying straight wire and solenoid"
          ],
          "source": {
            "pdf": "jee-main-2026.pdf",
            "page": 5
          }
        },
        {
          "number": 14,
          "title": "Electromagnetic Induction and Alternating Currents",
          "topics": [
            "Electromagnetic induction: Faraday's law, induced emf and current, Lenz’s law, eddy currents, self and mutual inductance",
            "Alternating currents, peak and RMS value of alternating current/voltage, reactance and impedance, LCR series circuit, resonance, power in AC circuits, wattless current, AC generator and transformer"
          ],
          "source": {
            "pdf": "jee-main-2026.pdf",
            "page": 5
          }
        },
        {
          "number": 15,
          "title": "Electromagnetic Waves",
          "topics": [],
          "source": {
            "pdf": "jee-main-2026.pdf",
            "page": 5
          }
        },
        {
          "number": 16,
          "title": "Optics",
          "topics": [
            "Reflection of light, spherical mirrors, mirror formula",
            "Wave optics: wavefront and Huygens ‘Principle, laws of reflection and refraction using Huygens principle",
            "Interference: Young's double-slit experiment and expression for fringe width, coherent sources and sustained interference of light",
            "Diffraction due to a single slit, width of central maximum",
            "Polarization: plane-polarized light, Brewster's law, uses of plane- polarized light and Polaroid"
          ],
          "source": {
            "pdf": "jee-main-2026.pdf",
            "page": 5
          }
        },
        {
          "number": 17,
          "title": "Dual Nature of Matter and Radiation",
          "topics": [
            "Dual nature of radiation, Photoelectric effect, Hertz and Lenard's observations, Einstein's photoelectric equation, particle nature of light",
            "Matter waves: wave nature of particle, de- Broglie relation"
          ],
          "source": {
            "pdf": "jee-main-2026.pdf",
            "page": 6
          }
        },
        {
          "number": 18,
          "title": "Atoms and Nuclei",
          "topics": [
            "Alpha-particle scattering experiment, Rutherford's model of atom, Bohr model, energy levels, hydrogen spectrum",
            "Composition and size of nucleus, atomic masses, mass-energy relation, mass defect, binding energy per nucleon and its variation with mass number, nuclear fission and fusion"
          ],
          "source": {
            "pdf": "jee-main-2026.pdf",
            "page": 6
          }
        },
        {
          "number": 19,
          "title": "Electronic Devices",
          "topics": [
            "Semiconductors, semiconductor diode: I-V characteristics in forward and reverse bias, diode as a rectifier",
            "I-V characteristics of LED, the photodiode, solar cell, Zener diode, Zener diode as a voltage regulator",
            "Logic gates (OR",
            "NAND and NOR)"
          ],
          "source": {
            "pdf": "jee-main-2026.pdf",
            "page": 6
          }
        },
        {
          "number": 20,
          "title": "Experimental Skills",
          "topics": [
            "Familiarity with the basic approach and observations of the experiments and activities: 1",
            "Vernier calipers -its use to measure the internal and external diameter and depth of a vessel",
            "Screw gauge-its use to determine the thickness/ diameter of thin sheet/wire",
            "Simple pendulum-dissipation of energy by plotting a graph between the square of amplitude and time",
            "Metre scale - the mass of a given object by the principle of moments",
            "Young's modulus of elasticity of the material of a metallic wire",
            "Surface tension of water by capillary rise and effect of detergents, 7",
            "Co-efficient of viscosity of a given viscous liquid by measuring the terminal velocity of a given spherical body",
            "Speed of sound in air at room temperature using a resonance tube, 9",
            "Specific heat capacity of a given (i) solid and (ii) liquid by method of mixtures",
            "The resistivity of the material of a given wire using a metre bridge",
            "The resistance of a given wire using Ohm's law",
            "Resistance and figure of merit of a galvanometer by half deflection method",
            "The focal length of (i) Convex mirror (ii) Concave mirror and (iii)Convex lens, using the parallax method",
            "The plot of the angle of deviation vs angle of incidence for a triangular prism",
            "The refractive index of a glass slab using a travelling microscope",
            "Characteristic curves of a p-n junction diode in forward and reverse bias",
            "Characteristic curves of a Zener diode and finding reverse breakdown voltage",
            "Identification of diode, LED, resistor, a capacitor from a mixed collection of such items CHEMISTRY PHYSICAL CHEMISTRY"
          ],
          "source": {
            "pdf": "jee-main-2026.pdf",
            "page": 6
          }
        }
      ]
    },
    {
      "id": "chemistry",
      "units": [
        {
          "number": 1,
          "title": "SOME BASIC CONCEPTS IN CHEMISTRY",
          "topics": [],
          "source": {
            "pdf": "jee-main-2026.pdf",
            "page": 7
          }
        },
        {
          "number": 2,
          "title": "ATOMIC STRUCTURE",
          "topics": [],
          "source": {
            "pdf": "jee-main-2026.pdf",
            "page": 7
          }
        },
        {
          "number": 3,
          "title": "CHEMICAL BONDING AND MOLECULAR STRUCTURE",
          "topics": [
            "Kossel-Lewis approach to chemical bond formation, the concept of ionic and covalent bonds",
            "Ionic Bonding: Formation of ionic bonds, factors affecting the formation of ionic bonds",
            "calculation of lattice enthalpy",
            "Covalent Bonding: Concept of electronegativity, Fajan’s rule, dipole moment, Valence Shell Electron Pair Repulsion (VSEPR ) theory and shapes of simple molecules",
            "Quantum mechanical approach to covalent bonding: Valence bond theory - its important features, the concept of hybridization involving s, p and d orbitals, resonance",
            "Elementary idea of metallic bonding, hydrogen bonding and its applications"
          ],
          "source": {
            "pdf": "jee-main-2026.pdf",
            "page": 7
          }
        },
        {
          "number": 4,
          "title": "CHEMICAL THERMODYNAMICS",
          "topics": [
            "Fundamentals of thermodynamics: System and surroundings, extensive and intensive properties, state functions, entropy, types of processes",
            "The second law of thermodynamics - Spontaneity of processes, Δ S of the universe and Δ G of the system as criteria for spontaneity",
            "ΔG°(Standard Gibbs energy change) and equilibrium constant"
          ],
          "source": {
            "pdf": "jee-main-2026.pdf",
            "page": 7
          }
        },
        {
          "number": 5,
          "title": "SOLUTIONS",
          "topics": [],
          "source": {
            "pdf": "jee-main-2026.pdf",
            "page": 7
          }
        },
        {
          "number": 6,
          "title": "EQUILIBRIUM",
          "topics": [
            "Meaning of equilibrium is the concept of dynamic equilibrium",
            "Equilibria involving physical processes: Solid-liquid, liquid-gas, gas-gas and solid-gas equilibria, Henry's law",
            "General characteristics of equilibrium involving physical processes"
          ],
          "source": {
            "pdf": "jee-main-2026.pdf",
            "page": 8
          }
        },
        {
          "number": 7,
          "title": "REDOX REACTIONS AND ELECTROCHEMISTRY",
          "topics": [
            "Electronic concepts of oxidation and reduction, redox reactions, oxidation number, rules for assigning oxidation number and balancing of redox reactions",
            "Electrolytic and metallic conduction, conductance in electrolytic solutions, molar conductivities and their variation with concentration, Kohlrausch’s law and its applications"
          ],
          "source": {
            "pdf": "jee-main-2026.pdf",
            "page": 8
          }
        },
        {
          "number": 8,
          "title": "CHEMICAL KINETICS",
          "topics": [
            "INORGANIC CHEMISTRY"
          ],
          "source": {
            "pdf": "jee-main-2026.pdf",
            "page": 8
          }
        },
        {
          "number": 9,
          "title": "CLASSIFICATION OF ELEMENTS AND PERIODICITY IN PROPERTIES",
          "topics": [
            "Modern periodic law and present form of the periodic table, s, p",
            "d and f block elements, periodic trends in properties of elements atomic and ionic radii, ionization enthalpy, electron gain enthalpy, valence, oxidation states and chemical reactivity"
          ],
          "source": {
            "pdf": "jee-main-2026.pdf",
            "page": 8
          }
        },
        {
          "number": 10,
          "title": "p- BLOCK ELEMENTS",
          "topics": [],
          "source": {
            "pdf": "jee-main-2026.pdf",
            "page": 8
          }
        },
        {
          "number": 11,
          "title": "d - and f- BLOCK ELEMENTS",
          "topics": [
            "Inner Transition Elements Lanthanoids - Electronic configuration, oxidation states and Lanthanoid contraction",
            "Actinoids - Electronic configuration and oxidation states"
          ],
          "source": {
            "pdf": "jee-main-2026.pdf",
            "page": 8
          }
        },
        {
          "number": 12,
          "title": "COORDINATION COMPOUNDS",
          "topics": [
            "Introduction to coordination compounds",
            "ORGANIC CHEMISTRY"
          ],
          "source": {
            "pdf": "jee-main-2026.pdf",
            "page": 9
          }
        },
        {
          "number": 13,
          "title": "PURIFICATION AND CHARACTERISATION OF ORGANIC COMPOUNDS",
          "topics": [
            "Purification - Crystallization, sublimation, distillation, differential extraction and chromatography - principles and their applications",
            "Qualitative analysis - Detection of nitrogen, sulphur, phosphorus and halogens",
            "Quantitative analysis (basic principles only) - Estimation of carbon, hydrogen, nitrogen, halogens, sulphur and phosphorus",
            "Calculations of empirical formulae and molecular formulae, numerical problems in organic quantitative analysis,"
          ],
          "source": {
            "pdf": "jee-main-2026.pdf",
            "page": 9
          }
        },
        {
          "number": 14,
          "title": "SOME BASIC PRINCIPLES OF ORGANIC CHEMISTRY",
          "topics": [
            "Electronic displacement in a covalent bond - Inductive effect, electromeric effect, resonance and hyperconjugation",
            "Common types of organic reactions- Substitution, addition, elimination and rearrangement",
            "UNITS 15: HYDROCARBONS Classification, isomerism, IUPAC nomenclature, general methods of preparation, properties and reactions",
            "Alkanes - Conformations: Sawhorse and Newman projections (of ethane), mechanism of halogenation of alkanes",
            "Alkenes - Geometrical isomerism, mechanism of electrophilic addition, addition of hydrogen, halogens, water, hydrogen halides (Markownikoffs and peroxide effect), Ozonolysis and polymerization",
            "Alkynes - Acidic character, addition of hydrogen, halogens, water and hydrogen halides, polymerization",
            "Aromatic hydrocarbons - Nomenclature, benzene - structure and aromaticity, mechanism of electrophilic substitution, halogenation, nitration",
            "Friedel-Craft's alkylation and acylation, directive influence of the functional group in mono- substituted benzene"
          ],
          "source": {
            "pdf": "jee-main-2026.pdf",
            "page": 9
          }
        },
        {
          "number": 16,
          "title": "ORGANIC COMPOUNDS CONTAINING HALOGENS",
          "topics": [
            "General methods of preparation, properties and reactions, nature of C-X bond, mechanisms of substitution reactions",
            "Uses, environmental effects of chloroform, iodoform, freons and DDT"
          ],
          "source": {
            "pdf": "jee-main-2026.pdf",
            "page": 9
          }
        },
        {
          "number": 17,
          "title": "ORGANIC COMPOUNDS CONTAINING OXYGEN",
          "topics": [
            "General methods of preparation, properties, reactions and uses",
            "ALCOHOLS, PHENOLS AND ETHERS Alcohols: Identification of primary, secondary and tertiary alcohols, mechanism of dehydration",
            "Phenols: Acidic nature, electrophilic substitution reactions, halogenation, nitration and sulphonation, Reimer - Tiemann reaction",
            "Ethers: Structure",
            "Aldol condensation, Cannizzaro reaction, Haloform reaction, chemical tests to distinguish between aldehydes and ketones",
            "Carboxylic Acids: Acidic strength and factors affecting it"
          ],
          "source": {
            "pdf": "jee-main-2026.pdf",
            "page": 10
          }
        },
        {
          "number": 18,
          "title": "ORGANIC COMPOUNDS CONTAINING NITROGEN",
          "topics": [
            "General methods of preparation, properties, reactions and uses",
            "Amines: Nomenclature, classification, structure, basic character and identification of primary, secondary and tertiary amines and their basic character",
            "Diazonium Salts: Importance in synthetic organic chemistry"
          ],
          "source": {
            "pdf": "jee-main-2026.pdf",
            "page": 10
          }
        },
        {
          "number": 19,
          "title": "BIOMOLECULES",
          "topics": [
            "General introduction and importance of biomolecules",
            "CARBOHYDRATES – Classification, aldoses and ketoses, monosaccharides (glucose and fructose) and constituent monosaccharides of oligosaccharides (sucrose, lactose and maltose)",
            "PROTEINS - Elementary idea of � -amino acids, peptide bond, polypeptides, proteins: primary, secondary, tertiary and quaternary structure (qualitative idea only), denaturation of proteins, enzymes",
            "VITAMINS – Classification and functions",
            "NUCLEIC ACIDS – Chemical constitution of DNA and RNA, biological functions of nucleic acids",
            "Hormones (General introduction)"
          ],
          "source": {
            "pdf": "jee-main-2026.pdf",
            "page": 10
          }
        },
        {
          "number": 20,
          "title": "PRINCIPLES RELATED TO PRACTICAL CHEMISTRY",
          "topics": [
            " The chemistry involved in the preparation of the following: Inorganic compounds, Mohr’s salt, potash alum",
            "Organic compounds: Acetanilide, p-nitro acetanilide, aniline yellow, iodoform",
            "Chemical principles involved in the following experiments: 1",
            "Enthalpy of solution of CuSO4 2",
            "Enthalpy of neutralization of strong acid and strong base",
            "Preparation of lyophilic and lyophobic sols",
            "Kinetic study of the reaction of iodide ions with hydrogen peroxide at room temperature"
          ],
          "source": {
            "pdf": "jee-main-2026.pdf",
            "page": 10
          }
        }
      ]
    }
  ]
} as const

export const unitCount = 53
