// GENERATED by scripts/curriculum/build-exams.mjs — do not edit by hand.
//
// Source:     https://cdnbbsr.s3waas.gov.in/s37bc1ec1d9c3426357e69acd5bf320061/uploads/2026/01/202601081066816297.pdf
// Discovered: https://neet.nta.nic.in/  (link text: "Syllabus for NEET (UG)-2026 Examination")
// sha256:     8b16375b6143a29743d3392915bbed0f886d3764f2f2d17932faa0b852a3a089
//
// Every unit carries the page it was read from. A claim that cannot name its
// page is a claim nobody can check.
import type { ExamSyllabus } from '../../types'

export const neet_ug_2026: ExamSyllabus = {
  "id": "neet-ug-2026",
  "source": {
    "url": "https://cdnbbsr.s3waas.gov.in/s37bc1ec1d9c3426357e69acd5bf320061/uploads/2026/01/202601081066816297.pdf",
    "discoveredFrom": "https://neet.nta.nic.in/",
    "linkText": "Syllabus for NEET (UG)-2026 Examination",
    "sha256": "8b16375b6143a29743d3392915bbed0f886d3764f2f2d17932faa0b852a3a089"
  },
  "subjects": [
    {
      "id": "physics",
      "units": [
        {
          "number": 1,
          "title": "PHYSICS AND MEASUREMENT",
          "topics": [],
          "source": {
            "pdf": "neet-ug-2026.pdf",
            "page": 4
          }
        },
        {
          "number": 2,
          "title": "KINEMATICS",
          "topics": [
            "The frame of reference, motion in a straight line, Position- time graph, speed and velocity",
            "Addition and subtraction, , scalar and vector products, Unit Vector, Resolution of a Vector",
            "Relative Velocity, Motion in a plane, Projectile Motion, Uniform Circular Motion"
          ],
          "source": {
            "pdf": "neet-ug-2026.pdf",
            "page": 4
          }
        },
        {
          "number": 3,
          "title": "LAWS OF MOTION",
          "topics": [
            "Force and inertia, Newton’s First law of motion",
            "Momentum, Newton’s Second Law of motion, Impulses",
            "Newton’s Third Law of motion",
            "Law of conservation of linear momentum and its applications",
            "Equilibrium of concurrent forces",
            "Static and Kinetic friction, laws of friction, rolling friction",
            "Dynamics of uniform circular motion: centripetal force and its applications: vehicle on a level circular road, vehicle on a banked road"
          ],
          "source": {
            "pdf": "neet-ug-2026.pdf",
            "page": 4
          }
        },
        {
          "number": 4,
          "title": "WORK, ENERGY, AND POWER",
          "topics": [
            "Work done by a constant force and a variable force",
            "kinetic and potential energies, work-energy theorem, power",
            "The potential energy of spring conservation of mechanical energy, conservative and non- conservative forces",
            "motion in a vertical circle: Elastic and inelastic collisions in one and two dimensions"
          ],
          "source": {
            "pdf": "neet-ug-2026.pdf",
            "page": 4
          }
        },
        {
          "number": 5,
          "title": "ROTATIONAL MOTION",
          "topics": [
            "Centre of the mass of a two-particle system, Centre of the mass of a rigid body",
            "Basic concepts of rotational motion",
            "moment of a force",
            "torque, angular momentum, conservation of angular momentum and its applications",
            "The moment of inertia, the radius of gyration, values of moments of inertia forsimple geometrical objects, parallel and perpendicular axes theorems, and their applications",
            "Equilibrium of rigid bodies, rigid body rotation and equations of rotational motion , comparison of linear and rotational motions",
            "2 1 1 File No",
            "U-14023/19/NEET(UGExam)/UGMEB CDN-20011/289/2024-COORDINATION-NMC (Computer (Computer No",
            "8376599) No"
          ],
          "source": {
            "pdf": "neet-ug-2026.pdf",
            "page": 4
          }
        },
        {
          "number": 6,
          "title": "GRAVITATION",
          "topics": [
            "The universal law of gravitation",
            "Acceleration due to gravity and its variation with altitude and depth",
            "Kepler’s law of planetary motion",
            "Gravitational potential energy",
            "gravitational potential",
            "Escape velocity, Motion of a satellite, orbital velocity, time period and energy of satellite"
          ],
          "source": {
            "pdf": "neet-ug-2026.pdf",
            "page": 5
          }
        },
        {
          "number": 7,
          "title": "PROPERTIES OF SOLIDS AND LIQUIDS",
          "topics": [
            "Elastic behaviour, Stress-strain relationship, Hooke's Law",
            "Young's modulus, bulk modulus, modulus of rigidity",
            "Pressure due to a fluid column",
            "Pascal's law and its applications",
            "Effect of gravity on fluid pressure",
            "Viscosity",
            "Stokes' law",
            "terminal velocity, streamline, and turbulent flow.critical velocity",
            "Bernoulli's principle and its applications",
            "Surface energy and surface tension, angle of contact, excess of pressure across a curved surface, application of surface tension - drops, bubbles, and capillary rise",
            "Heat, temperature, thermal expansion",
            "specific heat capacity, calorimetry",
            "change of state, latent heat",
            "Heat transfer- conduction, convection, and radiation"
          ],
          "source": {
            "pdf": "neet-ug-2026.pdf",
            "page": 5
          }
        },
        {
          "number": 8,
          "title": "THERMODYNAMICS",
          "topics": [
            "Thermal equilibrium, zeroth law of thermodynamics, the concept of temperature",
            "Heat, work, and internal energy",
            "The first law of thermodynamics, isothermal and adiabatic processes",
            "The second law of thermodynamics: reversible and irreversible processes"
          ],
          "source": {
            "pdf": "neet-ug-2026.pdf",
            "page": 5
          }
        },
        {
          "number": 9,
          "title": "KINETIC THEORY OF GASES",
          "topics": [
            "Equation of state of a perfect gas, work done on compressing a gas, Kinetic theory of gases - assumptions, the concept of pressure",
            "Kinetic interpretation of temperature: RMS speed of gas molecules: Degrees of freedom",
            "Law of equipartition of energy and applications to specific heat capacities of gases",
            "Mean free path",
            "Avogadro's number"
          ],
          "source": {
            "pdf": "neet-ug-2026.pdf",
            "page": 5
          }
        },
        {
          "number": 10,
          "title": "OSCILLATIONS AND WAVES",
          "topics": [
            "Oscillations and periodic motion – time period, frequency, displacement as a function of time",
            "Periodic functions",
            "Simple harmonic motion (S.H.M.) and its equation",
            "phase: oscillations of a spring -restoring force and force constant: energy in S.H.M",
            "- Kinetic and potential energies",
            "Simple pendulum - derivation of expression for its time period: Wave motion",
            "Longitudinal and transverse waves, speed of travelling wave",
            "Displacement relation for a progressive wave",
            "Principle of superposition of waves, reflection of waves",
            "Standing waves in strings and organ pipes, fundamental mode and harmonics",
            "Beats"
          ],
          "source": {
            "pdf": "neet-ug-2026.pdf",
            "page": 5
          }
        },
        {
          "number": 11,
          "title": "ELECTROSTATICS",
          "topics": [
            "Electric charges: Conservation of charge",
            "Coulomb's law forces between two point charges, forces between multiple charges: superposition principle and continuous charge distribution",
            "Electric field: Electric field due to a point charge, Electric field lines",
            "Electric dipole, Electric field due to a dipole",
            "Torque on a dipole in a uniform electric field",
            "3 2 2 File No",
            "U-14023/19/NEET(UGExam)/UGMEB CDN-20011/289/2024-COORDINATION-NMC (Computer (Computer No",
            "8376599) No",
            "Gauss's law and its applications to find field due to infinitely long uniformly charged straight wire, uniformly charged infinite plane sheet, and uniformly charged thin spherical shell",
            "Electric potential and its calculation for a point charge, electric dipole and system of charges",
            "potential difference, Equipotential surfaces, Electrical potential energy of a system of two point charges and of electric dipole in an electrostatic field",
            "Conductors and insulators",
            "Energy stored in a capacitor"
          ],
          "source": {
            "pdf": "neet-ug-2026.pdf",
            "page": 5
          }
        },
        {
          "number": 12,
          "title": "CURRENT ELECTRICITY",
          "topics": [
            "Electric current",
            "Drift velocity, mobility and their relation with electric current.",
            "Ohm's law",
            "Electrical resistance.",
            "V-l characteristics of Ohmic and non-ohmic conductors",
            "Electrical energy and power",
            "Electrical resistivity and conductivity",
            "Series and parallel combinations of resistors",
            "Temperature dependence of resistance",
            "Internal resistance, potential difference and emf of a cell, a combination of cells in series and parallel",
            "Kirchhoff’s laws and their applications",
            "Wheatstone bridge",
            "Metre Bridge"
          ],
          "source": {
            "pdf": "neet-ug-2026.pdf",
            "page": 6
          }
        },
        {
          "number": 13,
          "title": "MAGNETIC EFFECTS OF CURRENT AND MAGNETISM",
          "topics": [
            "Biot - Savart law and its application to current carrying circular loop",
            "Ampere's law and its applications to infinitely long current carrying straight wire and solenoid",
            "Force on a moving charge in uniform magnetic and electric fields",
            "Force on a current-carrying conductor in a uniform magnetic field",
            "The force between two parallel currents carrying conductors-definition of ampere",
            "Torque experienced by a current loop in a uniform magnetic field: Moving coil galvanometer, its sensitivity, and conversion to ammeter and voltmeter",
            "Current loop as a magnetic dipole and its magnetic dipole moment",
            "Bar magnet as an equivalent solenoid, magnetic field lines",
            "Magnetic field due to a magnetic dipole (bar magnet) along its axis and perpendicular to its axis",
            "Torque on a magnetic dipole in a uniform magnetic field",
            "Para- , dia- and ferromagnetic substances with examples, effect of temperature on magnetic properties"
          ],
          "source": {
            "pdf": "neet-ug-2026.pdf",
            "page": 6
          }
        },
        {
          "number": 14,
          "title": "ELECTROMAGNETIC INDUCTION AND ALTERNATING CURRENTS",
          "topics": [
            "Electromagnetic induction: Faraday's law",
            "Induced emf and current: Lenz’s Law, Eddy currents",
            "Self and mutual inductance",
            "Alternating currents, peak and RMS value of alternating current/ voltage: reactance and impedance: LCR series circuit, resonance: power in AC circuits, wattless current",
            "AC generator and transformer"
          ],
          "source": {
            "pdf": "neet-ug-2026.pdf",
            "page": 6
          }
        },
        {
          "number": 15,
          "title": "ELECTROMAGNETIC WAVES",
          "topics": [
            "Displacement current",
            "Electromagnetic waves and their characteristics, Transverse nature of electromagnetic waves, Electromagnetic spectrum (radio waves, microwaves, infrared, visible, ultraviolet",
            "X-rays",
            "Gamma rays), Applications of e.m",
            "waves"
          ],
          "source": {
            "pdf": "neet-ug-2026.pdf",
            "page": 6
          }
        },
        {
          "number": 16,
          "title": "OPTICS",
          "topics": [
            "Reflection of light, spherical mirrors, morror formula",
            "Refraction of light at plane and spherical surfaces, thin lens formula and lens maker formula",
            "Total internal reflection and its applications",
            "4 3 3 File No",
            "U-14023/19/NEET(UGExam)/UGMEB CDN-20011/289/2024-COORDINATION-NMC (Computer (Computer No",
            "8376599) No",
            "Magnification",
            "Power of a Lens",
            "Combination of thin lenses in contact",
            "Refraction of light through a prism",
            "Microscope and Astronomical Telescope (reflecting and refracting ) and their magnifying powers",
            "Wave optics: wavefront and Huygens' principle",
            "Laws of reflection and refraction using Huygens principle",
            "Interference, Young's double-slit experiment and expression for fringe width, coherent sources, and sustained interference of light",
            "Diffraction due to a single slit, width of central maximum.",
            "Polarization, plane-polarized light: Brewster's law, uses of plane-polarized light and Polaroid"
          ],
          "source": {
            "pdf": "neet-ug-2026.pdf",
            "page": 6
          }
        },
        {
          "number": 17,
          "title": "DUAL NATURE OF MATTER AND RADIATION",
          "topics": [
            "Dual nature of radiation",
            "Photoelectric effect",
            "Hertz and Lenard's observations",
            "Einstein's photoelectric equation: particle nature of light",
            "Matter waves-wave nature of particle, de Broglie relation."
          ],
          "source": {
            "pdf": "neet-ug-2026.pdf",
            "page": 7
          }
        },
        {
          "number": 18,
          "title": "ATOMS AND NUCLEI",
          "topics": [
            "Alpha-particle scattering experiment",
            "Rutherford's model of atom",
            "Bohr model, energy levels, hydrogen spectrum",
            "Composition and size of nucleus, atomic masses, Mass-energy relation, mass defect",
            "binding energy per nucleon and its variation with mass number, nuclear fission, and fusion"
          ],
          "source": {
            "pdf": "neet-ug-2026.pdf",
            "page": 7
          }
        },
        {
          "number": 19,
          "title": "ELECTRONIC DEVICES",
          "topics": [
            "Semiconductors",
            "semiconductor diode: I-V characteristics in forward and reverse bias",
            "diode as a rectifier",
            "I-V characteristics of LED",
            "the photodiode, solar cell, and Zener diode",
            "Zener diode as a voltage regulator.",
            "Logic gates (OR",
            "NAND and NOR)"
          ],
          "source": {
            "pdf": "neet-ug-2026.pdf",
            "page": 7
          }
        },
        {
          "number": 20,
          "title": "EXPERIMENTAL SKILLS",
          "topics": [
            "Familiarity with the basic approach and observations of the experiments and activities: 1",
            "Vernier calipers-its use to measure the internal and external diameter and depth of a vessel",
            "Screw gauge-its use to determine thickness/ diameter of thin sheet/wire",
            "Simple Pendulum-dissipation of energy by plotting a graph between the square of amplitude and time",
            "Metre Scale - the mass of a given object by the principle of moments",
            "Young's modulus of elasticity of the material of a metallic wire",
            "Surf ace tension of water by capillary rise and effect of detergents, 7",
            "Co-efficient of Viscosity of a given viscous liquid by measuring terminal velocity of a given spherical body, 8",
            "Speed of sound in air at room temperature using a resonance tube, 9",
            "Specific heat capacity of a given (i) solid and (ii) liquid by method of mixtures",
            "The resistivity of the material of a given wire using a metre bridge",
            "The resistance of a given wire using Ohm's law",
            "Resistance and figure of merit of a galvanometer by half deflection method",
            "The focal length of",
            "(i) Convex mirror (ii) Concave mirror, and (ii) Convex lens, using the parallax method",
            "The plot of the angle of deviation vs angle of incidence for a triangular prism",
            "5 4 4 File No",
            "U-14023/19/NEET(UGExam)/UGMEB CDN-20011/289/2024-COORDINATION-NMC (Computer (Computer No",
            "8376599) No",
            "Refractive index of a glass slab using a travelling microscope",
            "Characteristic curves of a p-n junction diode in forward and reverse bias",
            "Characteristic curves of a Zener diode and finding reverse break down voltage",
            "Identification of Diode",
            "LED,",
            "Resistor",
            "A capacitor from a mixed collection of such items",
            "6 5 5 File No",
            "U-14023/19/NEET(UGExam)/UGMEB CDN-20011/289/2024-COORDINATION-NMC (Computer (Computer No",
            "8376599) No"
          ],
          "source": {
            "pdf": "neet-ug-2026.pdf",
            "page": 7
          }
        }
      ]
    },
    {
      "id": "chemistry",
      "units": [
        {
          "number": 1,
          "title": "SOME BASIC CONCEPTS IN CHEMISTRY",
          "topics": [
            "Matter and its nature, Dalton's atomic theory: Concept of atom, molecule, element, and compound:: Laws of chemical combination",
            "Atomic and molecular masses, mole concept, molar mass, percentage composition, empirical and molecular formulae: Chemical equations and stoichiometry"
          ],
          "source": {
            "pdf": "neet-ug-2026.pdf",
            "page": 9
          }
        },
        {
          "number": 2,
          "title": "ATOMIC STRUCTURE",
          "topics": [
            "Nature of electromagnetic radiation, photoelectric effect",
            "Spectrum of the hydrogen atom",
            "Bohr model of a hydrogen atom - its postulates, derivation of the relations for the energy of the electron and radii of the different orbits, limitations of Bohr's model",
            "Dual nature of matter, de Broglie's relationship",
            "Heisenberg uncertainty principle",
            "Elementary ideas of quantum mechanics, quantum mechanics, the quantum mechanical model of the atom, its important features",
            "Concept of atomic orbitals as one-electron wave functions: Variation of  and 2 with r for 1s and 2s orbitals",
            "various quantum numbers (principal, angular momentum, and magnetic quantum numbers) and their significance",
            "shapes of s, p, and d - orbitals, electron spin and spin quantum number: Rules for filling electrons in orbitals – Aufbau principle",
            "Pauli's exclusion principle and Hund's rule, electronic configuration of elements, extra stability of half-filled and completely filled orbitals"
          ],
          "source": {
            "pdf": "neet-ug-2026.pdf",
            "page": 9
          }
        },
        {
          "number": 3,
          "title": "CHEMICAL BONDING AND MOLECULAR STRUCTURE",
          "topics": [
            "Kossel - Lewis approach to chemical bond formation, the concept of ionic and covalent bonds",
            "Ionic Bonding: Formation of ionic bonds, factors affecting the formation of ionic bonds",
            "calculation of lattice enthalpy",
            "Covalent Bonding: Concept of electronegativity",
            "Fajan’s rule, dipole moment: Valence Shell Electron Pair Repulsion (VSEPR ) theory and shapes of simple molecules",
            "Quantum mechanical approach to covalent bonding: Valence bond theory - its important features, the concept of hybridization involving s, p, and d orbitals",
            "Resonance",
            "Molecular Orbital Theory - Its important features",
            "Elementary idea of metallic bonding",
            "Hydrogen bonding and its applications"
          ],
          "source": {
            "pdf": "neet-ug-2026.pdf",
            "page": 9
          }
        },
        {
          "number": 4,
          "title": "CHEMICAL THERMODYNAMICS",
          "topics": [
            "Fundamentals of thermodynamics: System and surroundings, extensive and intensive properties, state functions, types of processes",
            "The first law of thermodynamics - Concept of work, heat internal energy and enthalpy, heat capacity, molar heat capacity",
            "Hess’s law of constant heat summation",
            "Enthalpies of bond 7 6 6 File No",
            "U-14023/19/NEET(UGExam)/UGMEB CDN-20011/289/2024-COORDINATION-NMC (Computer (Computer No",
            "8376599) No",
            "The second law of thermodynamics - Spontaneity of processes",
            "S of the universe and G of the system as criteria for spontaneity",
            "G (Standard Gibbs energy change) and equilibrium constant"
          ],
          "source": {
            "pdf": "neet-ug-2026.pdf",
            "page": 9
          }
        },
        {
          "number": 5,
          "title": "SOLUTIONS",
          "topics": [
            "Colligative properties of dilute solutions - a relative lowering of vapour pressure, depression of freezing point, the elevation of boiling point and osmotic pressure",
            "Determination of molecular mass using colligative properties",
            "Abnormal value of molar mass, van’t Hoff factor and its significance"
          ],
          "source": {
            "pdf": "neet-ug-2026.pdf",
            "page": 10
          }
        },
        {
          "number": 6,
          "title": "EQUILIBRIUM",
          "topics": [
            "Meaning of equilibrium, the concept of dynamic equilibrium",
            "Equilibria involving physical processes: Solid-liquid, liquid - gas and solid-gas equilibria, Henry's law",
            "General characteristics of equilibrium involving physical processes",
            "Le Chatelier’s principle",
            "Ionic equilibrium: Weak and strong electrolytes, ionization of electrolytes, various concepts of acids and bases (Arrhenius",
            "Bronsted - Lowry and Lewis) and their ionization, acid-base equilibria (including multistage ionization) and ionization constants, ionization of water",
            "pH scale, common ion effect, hydrolysis of salts and pH of their solutions, the solubility of sparingly soluble salts and solubility products, buffer solutions"
          ],
          "source": {
            "pdf": "neet-ug-2026.pdf",
            "page": 10
          }
        },
        {
          "number": 7,
          "title": "REDOX REACTIONS AND ELECTROCHEMISTRY",
          "topics": [
            "Electronic concepts of oxidation and reduction, redox reactions, oxidation number, rules for assigning oxidation number, balancing of redox reactions",
            "Electrolytic and metallic conduction, conductance in electrolytic solutions, molar conductivities and their variation with concentration: Kohlrausch’s law and its applications",
            "Relationship between cell potential and Gibbs' energy change: Dry cell and lead accumulator",
            "Fuel cells"
          ],
          "source": {
            "pdf": "neet-ug-2026.pdf",
            "page": 10
          }
        },
        {
          "number": 8,
          "title": "CHEMICAL KINETICS",
          "topics": [
            "Rate of a chemical reaction, factors affecting the rate of reactions: concentration, temperature, pressure, and catalyst",
            "elementary and complex reactions, order and molecularity of reactions, rate law, rate constant and its units, differential and integral forms of zero and first-order 8 7 7 File No",
            "U-14023/19/NEET(UGExam)/UGMEB CDN-20011/289/2024-COORDINATION-NMC (Computer (Computer No",
            "8376599) No",
            "INORGANIC CHEMISTRY"
          ],
          "source": {
            "pdf": "neet-ug-2026.pdf",
            "page": 10
          }
        },
        {
          "number": 9,
          "title": "CLASSIFICATION OF ELEMENTS AND PERIODICITY IN PROPERTIES",
          "topics": [
            "Modem periodic law and present form of the periodic table, s, p",
            "d and f block elements, periodic trends in properties of elements atomic and ionic radii, ionization enthalpy, electron gain enthalpy, valence, oxidation states, and chemical reactivity"
          ],
          "source": {
            "pdf": "neet-ug-2026.pdf",
            "page": 11
          }
        },
        {
          "number": 10,
          "title": "P- BLOCK ELEMENTS",
          "topics": [
            "Group -13 to Group 18 Elements General Introduction: Electronic configuration and general trends in physical and chemical properties of elements across the periods and down the groups",
            "unique behaviour of the first element in each group"
          ],
          "source": {
            "pdf": "neet-ug-2026.pdf",
            "page": 11
          }
        },
        {
          "number": 11,
          "title": "d - and f- BLOCK ELEMENTS",
          "topics": [
            "Preparation, properties, and uses of K2Cr2O7, and KMnO4",
            "Inner Transition Elements Lanthanoids - Electronic configuration, oxidation states, and lanthanoid contraction",
            "Actinoids - Electronic configuration and oxidation states"
          ],
          "source": {
            "pdf": "neet-ug-2026.pdf",
            "page": 11
          }
        },
        {
          "number": 12,
          "title": "CO-ORDINATION COMPOUNDS",
          "topics": [
            "Introduction to coordination compounds",
            "Werner's theory",
            "ligands, coordination number, denticity",
            "chelation",
            "IUPAC nomenclature of mononuclear co-ordination compounds, isomerism",
            "Bonding-Valence bond approach and basic ideas of Crystal field theory, colour and magnetic properties",
            "Importance of co-ordination compounds (in qualitative analysis, extraction of metals and in biological systems)",
            "ORGANIC CHEMISTRY"
          ],
          "source": {
            "pdf": "neet-ug-2026.pdf",
            "page": 11
          }
        },
        {
          "number": 13,
          "title": "PURIFICATION AND CHARACTERISATION OF ORGANIC COMPOUNDS",
          "topics": [
            "Purification - Crystallization, sublimation, distillation, differential extraction, and chromatography - principles and their applications",
            "Qualitative analysis - Detection of nitrogen, sulphur, phosphorus, and halogens",
            "9 8 8 File No",
            "U-14023/19/NEET(UGExam)/UGMEB CDN-20011/289/2024-COORDINATION-NMC (Computer (Computer No",
            "8376599) No",
            "Calculations of empirical formulae and molecular formulae: Numerical problems in organic quantitative analysis,"
          ],
          "source": {
            "pdf": "neet-ug-2026.pdf",
            "page": 11
          }
        },
        {
          "number": 14,
          "title": "SOME BASIC PRINCIPLES OF ORGANIC CHEMISTRY",
          "topics": [
            "Homologous series: Isomerism - structural and stereoisomerism",
            "Nomenclature (Trivial and IUPAC) Covalent bond fission - Homolytic and heterolytic: free radicals, carbocations, and carbanions",
            "stability of carbocations and free radicals, electrophiles, and nucleophiles",
            "Electronic displacement in a covalent bond - Inductive effect, electromeric effect, resonance, and hyperconjugation",
            "Common types of organic reactions- Substitution, addition, elimination, and rearrangement",
            "UNITS 15: HYDROCARBONS Classification, isomerism, IUPAC nomenclature, general methods of preparation, properties, and reactions",
            "Alkanes - Conformations: Sawhorse and Newman projections (of ethane): Mechanism of halogenation of alkanes",
            "Alkenes - Geometrical isomerism: Mechanism of electrophilic addition: addition of hydrogen, halogens, water, hydrogen halides (Markownikoffs and peroxide effect): Ozonolysis and polymerization",
            "Alkynes - Acidic character: Addition of hydrogen, halogens, water, and hydrogen halides: Polymerization",
            "Aromatic hydrocarbons - Nomenclature, benzene - structure and aromaticity: Mechanism of electrophilic substitution: halogenation, nitration",
            "Friedel - Craft's alkylation and acylation, directive influence of the functional group in mono- substituted benzene"
          ],
          "source": {
            "pdf": "neet-ug-2026.pdf",
            "page": 12
          }
        },
        {
          "number": 16,
          "title": "ORGANIC COMPOUNDS CONTAINING HALOGENS",
          "topics": [
            "General methods of preparation, properties, and reactions",
            "Nature of C-X bond",
            "Mechanisms of substitution reactions",
            "Uses",
            "Environmental effects of chloroform, iodoform freons, and DDT"
          ],
          "source": {
            "pdf": "neet-ug-2026.pdf",
            "page": 12
          }
        },
        {
          "number": 17,
          "title": "ORGANIC COMPOUNDS CONTAINING OXYGEN",
          "topics": [
            "General methods of preparation, properties, reactions, and uses",
            "ALCOHOLS, PHENOLS, AND ETHERS 10 9 9 File No",
            "U-14023/19/NEET(UGExam)/UGMEB CDN-20011/289/2024-COORDINATION-NMC (Computer (Computer No",
            "8376599) No",
            "Phenols: Acidic nature, electrophilic substitution reactions: halogenation",
            "nitration and sulphonation",
            "Reimer - Tiemann reaction",
            "Ethers: Structure",
            "Aldehyde and Ketones: Nature of carbonyl group",
            "Nucleophilic addition to >C=O group, relative reactivities of aldehydes and ketones",
            "Important reactions such as - Nucleophilic addition reactions (addition of HCN",
            "NH3, and its derivatives), Grignard reagent",
            "oxidation: reduction (Wolf Kishner and Clemmensen)",
            "the acidity of -hydrogen",
            "aldol condensation, Cannizzaro reaction",
            "Haloform reaction, Chemical tests to distinguish between aldehydes and Ketones",
            "Carboxylic Acids Acidic strength and factors affecting it,"
          ],
          "source": {
            "pdf": "neet-ug-2026.pdf",
            "page": 12
          }
        },
        {
          "number": 18,
          "title": "ORGANIC COMPOUNDS CONTAINING NITROGEN",
          "topics": [
            "General methods of preparation",
            "Properties, reactions, and uses",
            "Amines: Nomenclature, classification structure, basic character, and identification of primary, secondary, and tertiary amines and their basic character",
            "Diazonium Salts: Importance in synthetic organic chemistry"
          ],
          "source": {
            "pdf": "neet-ug-2026.pdf",
            "page": 13
          }
        },
        {
          "number": 19,
          "title": "BIOMOLECULES",
          "topics": [
            "General introduction and importance of biomolecules",
            "CARBOHYDRATES - Classification",
            "aldoses and ketoses: monosaccharides (glucose and fructose) and constituent monosaccharides of oligosaccharides (sucrose, lactose, and maltose)",
            "PROTEINS - Elementary Idea of -amino acids, peptide bond, polypeptides",
            "Proteins: primary, secondary, tertiary, and quaternary structure (qualitative idea only), denaturation of proteins, enzymes",
            "VITAMINS – Classification and functions",
            "NUCLEIC ACIDS – Chemical constitution of DNA and RNA",
            "Biological functions of nucleic acids",
            "Hormones (General introduction)"
          ],
          "source": {
            "pdf": "neet-ug-2026.pdf",
            "page": 13
          }
        },
        {
          "number": 20,
          "title": "PRINCIPLES RELATED TO PRACTICAL CHEMISTRY",
          "topics": [
            "Detection of extra elements (Nitrogen, Sulphur, halogens) in organic compounds",
            "Detection of the following functional groups",
            "hydroxyl (alcoholic and phenolic), carbonyl (aldehyde and ketones) carboxyl, and amino groups in organic compounds",
            " The chemistry involved in the preparation of the following: Inorganic compounds",
            "Mohr’s salt, potash alum",
            "Organic compounds: Acetanilide, p-nitro acetanilide, aniline yellow, iodoform",
            "11 10 10 File No",
            "U-14023/19/NEET(UGExam)/UGMEB CDN-20011/289/2024-COORDINATION-NMC (Computer (Computer No",
            "8376599) No",
            "3 4 Chemical principles involved in the following experiments: 1",
            "Enthalpy of solution of CuSO4 2",
            "Enthalpy of neutralization of strong acid and strong base",
            "Preparation of lyophilic and lyophobic sols",
            "Kinetic study of the reaction of iodide ions with hydrogen peroxide at room temperature",
            "12 11 11 File No",
            "U-14023/19/NEET(UGExam)/UGMEB CDN-20011/289/2024-COORDINATION-NMC (Computer (Computer No",
            "8376599) No"
          ],
          "source": {
            "pdf": "neet-ug-2026.pdf",
            "page": 13
          }
        }
      ]
    },
    {
      "id": "biology",
      "units": [
        {
          "number": 1,
          "title": "Diversity in Living World",
          "topics": [
            "• What is living?",
            "Biodiversity",
            "Need for classification;",
            "Taxonomy & Systematics",
            "Concept of species and taxonomical hierarchy",
            "Binomial nomenclature",
            "• Five kingdom classification",
            "salient features and classification of Monera",
            "Protista and Fungi into major groups",
            "Lichens",
            "Viruses and Viroids",
            "• Salient features and classification of animals-nonchordate up to phyla level and chordate up to classes level (three to five salient features and at least two examples)"
          ],
          "source": {
            "pdf": "neet-ug-2026.pdf",
            "page": 15
          }
        },
        {
          "number": 2,
          "title": "Structural Organisation in Animals and Plants",
          "topics": [
            "• Morphology and modifications",
            "Tissues",
            "• Animal tissues",
            "Morphology, anatomy and functions of different systems (digestive, circulatory, respiratory, nervous and reproductive) of an insect (Frog)",
            "(Brief account only)"
          ],
          "source": {
            "pdf": "neet-ug-2026.pdf",
            "page": 15
          }
        },
        {
          "number": 3,
          "title": "Cell Structure and Function",
          "topics": [
            "• Cell theory and cell as the basic unit of life",
            "Structure of prokaryotic and eukaryotic cell",
            "Plant cell and animal cell",
            "Cell envelope, cell membrane, cell wall",
            "Cell organelles- structure and function",
            "Endomembrane system-endoplasmic reticulum, Golgi bodies, lysosomes, vacuoles",
            "mitochondria, ribosomes, plastids, micro bodies",
            "Cytoskeleton, cilia, flagella, centrioles (ultra structure and function)",
            "Nucleus-nuclear membrane, chromatin, nucleolus",
            "• Chemical constituents of living cells: Biomolecules-structure and function of proteins, carbodydrates, lipids, nucleic acids",
            "Enzymes-types, properties, enzyme action, classification and nomenclature of anzymes • B Cell division: Cell cycle, mitosis, meiosis and their significance"
          ],
          "source": {
            "pdf": "neet-ug-2026.pdf",
            "page": 15
          }
        },
        {
          "number": 4,
          "title": "Plant Physiology",
          "topics": [
            "• Photosynthesis: Photosynthesis as a means of Autotrophic nutrition",
            "Site of photosynthesis take place",
            "pigments involved in Photosynthesis (Elementary idea)",
            "Photochemical and biosynthetic phases of photosynthesis",
            "Cyclic and non cyclic and 13 12 12 File No",
            "U-14023/19/NEET(UGExam)/UGMEB CDN-20011/289/2024-COORDINATION-NMC (Computer (Computer No",
            "8376599) No",
            "Chemiosmotic hypothesis",
            "Photorespiration C3 and C4 pathways",
            "Factors affecting photosynthesis",
            "• Respiration: Exchange gases",
            "Cellular respiration-glycolysis, fermentation (anaerobic), TCA cycle and electron transport system (aerobic)",
            "Energy relations- Number of ATP molecules generated",
            "Amphibolic pathways",
            "Respiratory quotient",
            "• Plant growth and development: Seed germination",
            "Phases of Plant growth and plant growth rate",
            "Conditions of growth",
            "Differentiation, dedifferentiation and redifferentiation",
            "Sequence of developmental process in a plant cell",
            "Growth regulators- auxin, gibberellin, cytokinin, ethylene, ABA"
          ],
          "source": {
            "pdf": "neet-ug-2026.pdf",
            "page": 15
          }
        },
        {
          "number": 5,
          "title": "Human Physiology",
          "topics": [
            "• Breathing and Respiration: Respiratory organs in animals (recall only)",
            "Respiratory system in humans",
            "Mechanism of breathing and its regulation in humans-Exchange of gases, transport of gases and regulation of respiration Respiratory volumes",
            "Disorders related to respiration-Asthma, Emphysema, Occupational respiratory disorders",
            "• Body fluids and circulation: Composition of blood, blood groups, coagulation of blood",
            "Composition of lymph and its function",
            "Human circulatory system-Structure of human heart and blood vessels",
            "Cardiac cycle, cardiac output, ECG, Double circulation",
            "Regulation of cardiac activity",
            "Disorders of circulatory system-Hypertension, Coronary artery disease, Angina pectoris, Heart failure",
            "• Excretory products and their elimination: Modes of excretion- Ammonotelism, ureotelism, uricotelism",
            "Human excretory system-structure and fuction",
            "Urine formation, Osmoregulation",
            "Regulation of kidney function-Renin-angiotensin, Atrial Natriuretic Factor, ADH and Diabetes insipidus",
            "Role of other organs in excretion",
            "Disorders",
            "Uraemia, Renal failure, Renal calculi, Nephritis",
            "Dialysis and artificial kidney",
            "• Locomotion and Movement: Types of movement- ciliary, fiagellar, muscular",
            "Skeletal muscle- contractile proteins and muscle contraction",
            "Skeletal system and its functions (To be dealt with the relevant practical of Practical syllabus)",
            "Joints",
            "Disorders of muscular and skeletal system-Myasthenia gravis, Tetany, Muscular dystrophy, Arthritis, Osteoporosis, Gout",
            "• Neural control and coordination: Neuron and nerves",
            "Nervous system in humanscentral nervous system, peripheral nervous system and visceral nervous system",
            "Generation and conduction of nerve impulse",
            "• Chemical coordination and regulation: Endocrine glands and hormones",
            "Human endocrine system-Hypothalamus, Pituitary, Pineal, Thyroid, Parathyroid, Adrenal, Pancreas, Gonads",
            "Mechanism of hormone action (Elementary Idea)",
            "Role of hormones as messengers and regulators, Hypo-and hyperactivity and related disorders (Common disorders e.g",
            "Dwarfism, Acromegaly, Cretinism, goiter, exopthalmic goiter, diabetes, Addison’s disease)",
            "(Imp: Diseases and disorders mentioned above to be dealt in brief.) 14 13 13 File No",
            "U-14023/19/NEET(UGExam)/UGMEB CDN-20011/289/2024-COORDINATION-NMC (Computer (Computer No",
            "8376599) No"
          ],
          "source": {
            "pdf": "neet-ug-2026.pdf",
            "page": 16
          }
        },
        {
          "number": 6,
          "title": "Reproduction",
          "topics": [
            "• Sexual reproduction in flowering plants: Flower structure",
            "Development of male and female gametophytes",
            "Pollination-types, agencies and examples",
            "Outbreeding devices",
            "Pollen-Pistil interaction",
            "Double fertilization",
            "Post fertilization events- Development of endosperm and embryo, Development of seed and formation of fruit",
            "Special modes- apomixis, parthenocarpy, polyembryony",
            "Significance of seed and fruit formation",
            "• Human Reproduction: Male and female reproductive systems",
            "Microscopic anatomy of testis and ovary",
            "Gametogenesis-spermatogenesis & oogenesis",
            "Menstrual cycle",
            "Fertilisation, embryo development upto blastocyst formation, implantation",
            "Pregnancy and placenta formation (Elementary idea)",
            "Parturition (Elementary idea)",
            "Lactation (Elementary idea)",
            "• Reproductive health: Need for reproductive health and prevention of sexually transmitted diseases (STD)",
            "Birth control-Need and Methods, Contraception and Medical Termination of Pregnancy (MTP)",
            "Amniocentesis",
            "Infertility and assisted reproductive technologies – IVF, ZIFT, GIFT (Elementary idea for general awareness)"
          ],
          "source": {
            "pdf": "neet-ug-2026.pdf",
            "page": 17
          }
        },
        {
          "number": 7,
          "title": "Genetics and Evolution",
          "topics": [
            "• Heredity and variation: Mendelian Inheritance",
            "Deviations from Mendelism- Incomplete dominance, Co-dominance, Multiple alleles and Inheritance of blood groups, Pleiotropy",
            "Elementary idea of polygenic inheritance",
            "Chromosome theory of inheritance",
            "Chromosomes and genes",
            "Sex determination-In humans, birds, honey bee",
            "Linkage and crossing over",
            "Sex linked inheritance-Haemophilia, Colour blindness",
            "Mendelian disorders in humans-Thalassemia",
            "Chromosomal disorders in humans",
            "Down’s syndrome, Turner’s and Klinefelter’s syndromes",
            "• Molecular basis of Inheritance: Search for genetic material and DNA as genetic material",
            "Structure of DNA and RNA",
            "DNA packaging",
            "DNA replication",
            "Central dogma",
            "Transcription, genetic code, translation",
            "Gene expression and regulation- Lac Operon",
            "Genome and human genome project",
            "DNA finger printing, protein biosynthesis",
            "• Evolution: Origin of life",
            "Biological evolution and evidences for biological evolution from Paleontology, comparative anatomy, embryology and molecular evidence)",
            "Darwin’s contribution, Modern Synthetic theory of Evolution",
            "Mechanism of evolution- Variation (Mutation and Recombination) and Natural Selection with examples, types of natural selection",
            "Gene flow and genetic drift",
            "Hardy-Weinberg’s principle",
            "Adaptive Radiation",
            "Human evolution"
          ],
          "source": {
            "pdf": "neet-ug-2026.pdf",
            "page": 17
          }
        },
        {
          "number": 8,
          "title": "Biology and Human Welfare",
          "topics": [
            "• Health and Disease",
            "Pathogens",
            "parasites causing human diseases (Malaria, Filariasis, Ascariasis",
            "Typhoid, Pneumonia, common cold, amoebiasis, ring worm, dengue, chikungunya)",
            "Basic concepts of immunology-vaccines",
            "Cancer, HIV and AIDS",
            "Adolescence, drug and alcohol abuse.Tobacco abuse 15 14 14 File No",
            "U-14023/19/NEET(UGExam)/UGMEB CDN-20011/289/2024-COORDINATION-NMC (Computer (Computer No",
            "8376599) No"
          ],
          "source": {
            "pdf": "neet-ug-2026.pdf",
            "page": 17
          }
        },
        {
          "number": 9,
          "title": "Biotechnology and Its Applications",
          "topics": [
            "• Principles and process of Biotechnology: Genetic engineering (Recombinant DNA technology)",
            "• Application of Biotechnology in health and agriculture: Human insulin and vaccine production, gene therapy",
            "Genetically modified organisms-Bt crops",
            "Transgenic Animals",
            "Biosafety issues-Biopiracy and patents"
          ],
          "source": {
            "pdf": "neet-ug-2026.pdf",
            "page": 18
          }
        },
        {
          "number": 10,
          "title": "Ecology and Environment",
          "topics": [
            "• Organisms and environmentPopulation interactions-mutualism, competition, predation, parasitism",
            "Population attributes-growth, birth rate and death rate, age distribution",
            "• Ecosystem: Patterns, components",
            "productivity and decomposition",
            "Energy flow",
            "Pyramids of number, biomass, energy • Biodiversity and its conservation: Concept of Biodiversity",
            "Patterns of Biodiversity",
            "Importance of Biodiversity",
            "Loss of Biodiversity",
            "Biodiversity conservation",
            "Hotspots, endangered organisms, extinction, Red Data Book, biosphere reserves, National parks and sanctuaries, Sacred Groves",
            "16 15 15 File No",
            "U-14023/19/NEET(UGExam)/UGMEB CDN-20011/289/2024-COORDINATION-NMC (Computer (Computer No",
            "8376599) No",
            "8303077) Generated from eOffice by Lalit SandipKumar Kumar, Khanna, Sr Consultant(SK)-, Consultant(LKK), CONSULTANT, SENIOR NMC on CONSULTANT, 04/12/2025 NMC12:13 on pm 22/12/2025 01:59 pm"
          ],
          "source": {
            "pdf": "neet-ug-2026.pdf",
            "page": 18
          }
        }
      ]
    }
  ]
} as const

export const unitCount = 49
