import {readFileSync} from 'node:fs';
const R=[];
const ver=async p=>(await import(`./node_modules/${p}/package.json`,{with:{type:'json'}})).default.version;
async function T(id,pkg,fn){let v='?';try{v=await ver(pkg)}catch{}
  try{const d=await fn();R.push({id,pkg,v,pass:true,d})}catch(e){R.push({id,pkg,v,pass:false,d:String(e.message||e).split('\n')[0].slice(0,110)})}}
function dom(){ // install a jsdom global environment for DOM-bound editors
  return import('jsdom').then(({JSDOM})=>{const j=new JSDOM('<!doctype html><div id=r></div>',{pretendToBeVisual:true});
    for(const k of ['window','document','navigator','HTMLElement','Element','Node','Range','Text','DocumentFragment','MutationObserver','getComputedStyle','DOMParser','XMLSerializer','KeyboardEvent','InputEvent','Event','CustomEvent'])
      if(globalThis[k]===undefined) globalThis[k]=k==='window'?j.window:j.window[k];
    return j;});
}
await T(253,'highlight.js',async()=>{const h=(await import('highlight.js')).default;
  const r=h.highlight('const a=1',{language:'javascript'});if(!r.value.includes('hljs-'))throw new Error(r.value);return 'highlight js -> '+r.value.slice(0,50)});
await T(258,'@babel/parser',async()=>{const {parse}=await import('@babel/parser');
  const a=parse('const x:number=1',{plugins:['typescript'],sourceType:'module'});
  if(a.program.body[0].type!=='VariableDeclaration')throw new Error('bad ast');return 'parsed TS -> '+a.program.body[0].type});
await T(236,'showdown',async()=>{const S=(await import('showdown')).default;
  const h=new S.Converter().makeHtml('# s');if(!h.includes('<h1'))throw new Error(h);return 'makeHtml -> '+h});
await T(227,'retext',async()=>{const {retext}=await import('retext');const {default:eq}=await import('retext-equality');
  const f=await retext().use(eq).process('He is a boss.');return 'ran retext-equality, '+f.messages.length+' message(s)'});
await T(232,'@mdx-js/mdx',async()=>{const {compile}=await import('@mdx-js/mdx');
  const c=String(await compile('# mdx\n\n<b>x</b>'));if(!c.includes('jsx'))throw new Error(c.slice(0,60));return 'compiled MDX to JSX module, '+c.length+' bytes'});
await T(264,'pdfjs-dist',async()=>{const pjs=await import('pdfjs-dist/legacy/build/pdf.mjs');
  const data=new Uint8Array(readFileSync('fixture.pdf'));
  const doc=await pjs.getDocument({data,useSystemFonts:false}).promise;const pg=await doc.getPage(1);
  const tc=await pg.getTextContent();const txt=tc.items.map(i=>i.str).join('').trim();
  if(!txt.includes('REGISTRY'))throw new Error('got '+JSON.stringify(txt));
  return `${doc.numPages}pg, extracted ${JSON.stringify(txt)}`});
await T(268,'pdfkit',async()=>{const PD=(await import('pdfkit')).default;
  const d=new PD({size:[200,100]});const chunks=[];d.on('data',c=>chunks.push(c));
  const done=new Promise(r=>d.on('end',r));d.fontSize(12).text('PDFKIT OK',10,40);d.end();await done;
  const b=Buffer.concat(chunks);if(b.subarray(0,4).toString()!=='%PDF')throw new Error('no PDF header');
  return 'generated PDF stream, '+b.length+' bytes'});
await T(263,'typescript',async()=>{const ts=(await import('typescript')).default;
  const o=ts.transpileModule('const f=(x:number):string=>`${x}`',{compilerOptions:{target:ts.ScriptTarget.ES2020}});
  if(o.outputText.includes(': number'))throw new Error('types not stripped');
  return 'tsc '+ts.version+' transpiled TS->JS -> '+o.outputText.trim()});
await T(259,'@swc/core',async()=>{const swc=await import('@swc/core');
  const o=swc.transformSync('const f=(x:number)=>x*2',{filename:'a.ts',jsc:{parser:{syntax:'typescript'}}});
  if(!o.code.includes('=>')&&!o.code.includes('function'))throw new Error(o.code);
  return 'transformSync TS->JS -> '+o.code.trim().slice(0,60)});
await T(262,'tsup',async()=>{const {build}=await import('tsup');
  const {mkdirSync,writeFileSync,readFileSync:rf,existsSync}=await import('node:fs');
  mkdirSync('tsup-src',{recursive:true});writeFileSync('tsup-src/e.ts','export const v:number=7');
  await build({entry:['tsup-src/e.ts'],outDir:'tsup-out',format:['esm'],silent:true,config:false});
  if(!existsSync('tsup-out/e.js'))throw new Error('no output');
  return 'built ts->esm, out = '+rf('tsup-out/e.js','utf8').trim()});
await T(218,'rdflib',async()=>{const $rdf=await import('rdflib');
  const s=$rdf.graph();$rdf.parse('<http://a/s> <http://a/p> "v" .',s,'http://a/','application/n-triples');
  if(s.statements.length!==1)throw new Error('stmts '+s.statements.length);
  return 'parsed N-Triples -> object='+s.statements[0].object.value});
await T(219,'@comunica/query-sparql',async()=>{const {QueryEngine}=await import('@comunica/query-sparql');
  const e=new QueryEngine();
  const bs=await e.queryBindings('SELECT ?o WHERE { ?s ?p ?o }',
    {sources:[{type:'serialized',value:'<http://a/s> <http://a/p> "cq" .',mediaType:'application/n-triples',baseIRI:'http://a/'}]});
  const arr=await bs.toArray();if(!arr.length)throw new Error('no bindings');
  return 'SPARQL over inline N-Triples -> ?o = '+arr[0].get('o').value});
await T(255,'tree-sitter',async()=>{const P=(await import('tree-sitter')).default;
  const p=new P();if(typeof p.parse!=='function')throw new Error('no parse()');
  return 'native binding loaded, Parser instance created (no grammar installed, so no parse run)'});
await T(239,'prosemirror-model',async()=>{const {Schema,DOMSerializer}=await import('prosemirror-model');
  const s=new Schema({nodes:{doc:{content:'p+'},p:{content:'text*',toDOM:()=>['p',0]},text:{}}});
  const d=s.node('doc',null,[s.node('p',null,[s.text('pm')])]);
  if(d.textContent!=='pm')throw new Error(d.textContent);
  return 'schema built, doc node textContent='+JSON.stringify(d.textContent)});
await T(241,'slate',async()=>{const {createEditor,Transforms,Editor}=await import('slate');
  const e=createEditor();e.children=[{type:'p',children:[{text:'sl'}]}];
  Transforms.insertText(e,'X',{at:{path:[0,0],offset:2}});
  const t=Editor.string(e,[]);if(t!=='slX')throw new Error(t);
  return 'editor created, transform applied -> '+JSON.stringify(t)});
await T(238,'lexical',async()=>{await dom();const {createEditor,$getRoot,$createParagraphNode,$createTextNode}=await import('lexical');
  const ed=createEditor({onError(e){throw e}});let out='';
  ed.update(()=>{const p=$createParagraphNode();p.append($createTextNode('lx'));$getRoot().clear().append(p)},{discrete:true});
  ed.getEditorState().read(()=>{out=$getRoot().getTextContent()});
  if(out!=='lx')throw new Error(JSON.stringify(out));
  return 'headless editor state updated -> '+JSON.stringify(out)});
await T(243,'quill',async()=>{const j=await dom();const Q=(await import('quill')).default;
  const el=globalThis.document.getElementById('r');const q=new Q(el);
  q.setText('qu');const t=q.getText().trim();if(t!=='qu')throw new Error(JSON.stringify(t));
  return 'mounted in jsdom, setText/getText -> '+JSON.stringify(t)});
await T(240,'@tiptap/core',async()=>{await dom();const {Editor}=await import('@tiptap/core');
  const {default:Doc}=await import('@tiptap/extension-document');
  const {default:Para}=await import('@tiptap/extension-paragraph');
  const {default:Txt}=await import('@tiptap/extension-text');
  const e=new Editor({extensions:[Doc,Para,Txt],content:'<p>tt</p>'});
  const t=e.getText();if(t!=='tt')throw new Error(JSON.stringify(t));
  return 'editor constructed in jsdom, getText -> '+JSON.stringify(t)});
for(const p of ['slate-react','@editorjs/editorjs','draft-js','@milkdown/core','@remirror/core','@blocknote/core','monaco-editor','openseadragon'])
  await T('ver-only',p,async()=>{throw new Error('DOM/bundler-bound: version measured, no headless smoke test attempted')});
const P=R.filter(r=>r.pass).length;
for(const r of R) console.log(`${r.pass?'PASS':'----'} id=${r.id} ${r.pkg}@${r.v} :: ${r.d}`);
console.log(`\nWAVE2/3 SMOKE: ${P}/${R.filter(r=>r.id!=='ver-only').length} testable passed`);
