import type { LearningBoard } from '../types/learningBoard'

/* LARGE TABLE — exactly at the cap, on purpose.
 *
 * MAX_TABLE_ROWS is 50. This table has exactly 50 rows, so it validates with
 * ZERO notices while sitting on the boundary: one more row and the validator
 * would truncate and say so. Testing at the limit catches an off-by-one that
 * testing at 20 rows never would.
 *
 * Rows are generated by formula, never by Math.random, so the fixture is the
 * same on every machine and in every run. Determinism is what lets a layout
 * test compare two loads and mean it.
 */

/* A rainfall-and-yield series: monotone inputs, a derived column, and a
 * judgement column that changes at a stated threshold. */
function rows(): (string | number)[][] {
  const out: (string | number)[][] = []
  for (let i = 0; i < 50; i += 1) {
    const year = 1975 + i
    /* A slow upward trend with a repeating seasonal wobble — deterministic,
     * and shaped enough that a reader can see something in it. */
    const rainfall = 640 + ((i * 37) % 220) + (i % 7) * 9
    const yieldTonnes = Math.round((rainfall * 0.0042 + 1.8) * 100) / 100
    out.push([year, rainfall, yieldTonnes, rainfall < 700 ? 'below average' : 'at or above'])
  }
  return out
}

export const DATA_LARGE_TABLE_BOARD: LearningBoard = {
  type: 'learning_board',
  version: 1,
  id: 'board-data-large-table',
  title: 'Fifty years of one field',
  subtitle: 'Rainfall against yield, one row per year',
  layout: 'flow',
  blocks: [
    {
      id: 'large-intro',
      type: 'explanation',
      title: 'Some questions need every row',
      content:
        'A summary would say that yield rises with rainfall, and that is true. It would not let you find the year that broke the pattern, or check whether the relationship holds in the dry years as well as the wet ones.\n\nWhen the question is about exceptions, the table is the visualisation.',
    },
    {
      id: 'large-table',
      type: 'table',
      eyebrow: 'THE SERIES',
      title: 'Annual rainfall and recorded yield, 1975–2024',
      columns: ['Year', 'Rainfall (mm)', 'Yield (t/ha)', 'Against average'],
      rows: rows(),
    },
    {
      id: 'large-callout',
      type: 'callout',
      tone: 'note',
      content:
        'Fifty rows is the most this board will show at once. A longer series is not refused — it is truncated, and the notice tells you how many rows you are not seeing, so a missing tail is never silent.',
    },
  ],
  metadata: { source: 'fixture' },
}
