/**
 * P12-T3 — screenshot baselines for the acceptance lessons.
 *
 * CLAUDE.md's "Verification honesty" section records that this repository has
 * no screenshot-regression tooling: zero uses of `toHaveScreenshot`, zero
 * baseline directories, and the PNGs under `e2e/report/shots/` are gitignored
 * manual captures. This is that gap.
 *
 * WHAT A SCREENSHOT CATCHES THAT NOTHING ELSE HERE DOES
 * ----------------------------------------------------
 * `token-invariance.spec.ts` proves every block of a given kind uses the same
 * tokens across lessons. It says nothing about whether the result LOOKS right:
 * a layout that overlaps two blocks, clips a table, or collapses a chart to
 * zero height passes every token assertion while being unusable.
 *
 * That is Goal 2's rule -- never clip, distort, or silently delete content --
 * and it is the one rule in this repository with no automated check at all.
 *
 * WHY THESE THREE LESSONS
 * -----------------------
 * They are the ones with genuinely different dominant forms: prose+simulation,
 * flowchart, and chart. Three archetypes, three layout paths. Screenshotting six
 * near-identical prose lessons would cost six baselines and cover one path.
 *
 * WHY reduced-motion IS THE ONLY PROJECT THAT MATTERS HERE
 * -------------------------------------------------------
 * Animation is the single largest source of screenshot flake. The config already
 * declares a `reduced-motion` project; running the visual suite there means the
 * page is settled by construction rather than by a timeout somebody tuned.
 *
 * BASELINES ARE PLATFORM-SPECIFIC, AND THAT IS NOT A DETAIL
 * ---------------------------------------------------------
 * Font rasterisation differs between macOS and Linux, so a baseline captured on
 * a laptop fails on every CI run. Playwright encodes the platform in the
 * snapshot name, and CI refuses to CREATE a missing baseline -- it fails
 * instead. Both facts matter: it means a missing Linux baseline is a loud
 * failure rather than a silent first-run pass, and it means these files must be
 * generated by CI and committed from its artefacts, never captured locally.
 */

import { expect, test, type Page } from '@playwright/test'

/* HASH URLS, and this was a real defect before it was a detail.
   The app uses a hash router, so `/canvas` serves index.html and the router
   falls back to `#/today`. The first version of these specs used path URLs and
   every route resolved to the SAME page: the accessibility baseline recorded
   one page three times and called it three routes. Measured by probe:
   `page.goto('/canvas')` ended at `http://127.0.0.1:5183/canvas#/today`. */
/** The three acceptance lessons with genuinely different dominant forms. */
/**
 * Wait until the route has actually RENDERED, not merely finished loading.
 *
 * `CanvasRoute` is `React.lazy`, so `networkidle` fires while the Suspense
 * fallback is still on screen. The first version of this file scanned that
 * fallback and reported a clean canvas -- a measurement of a spinner.
 *
 * Waiting on the CONDITION (the lesson toggle exists) rather than on a duration
 * is also what keeps this off the law gate's list of timing races.
 */
async function canvasReady(page: Page): Promise<void> {
  await page.getByRole('group', { name: 'Lesson' }).waitFor({ state: 'visible' })
}

const LESSONS: readonly { label: string; slug: string }[] = [
  { label: 'Physics', slug: 'gas' },
  { label: 'Civics', slug: 'bill' },
  { label: 'Machine learning', slug: 'ml' },
]

/**
 * How much difference is a difference.
 *
 * Not zero. Anti-aliasing varies by a pixel or two between otherwise identical
 * renders, and a zero-tolerance baseline fails on noise -- which is how a
 * screenshot suite gets deleted in its second week. 0.2% of pixels is far below
 * anything a human would call a layout change and far above the noise floor.
 */
const MAX_DIFF_RATIO = 0.002

test.describe('the acceptance lessons render without regressing', () => {
  for (const lesson of LESSONS) {
    test(`${lesson.slug} matches its baseline`, async ({ page }) => {
      await page.goto('/#/canvas')
      await page.waitForLoadState('networkidle')
      await canvasReady(page)

      /* Selected by its accessible name, not a class or an nth-child. A
         selector tied to structure breaks on every refactor and teaches people
         to regenerate baselines without looking, which is the failure mode this
         whole file is trying to avoid. */
      const button = page.getByRole('button', { name: lesson.label, exact: true })
      await expect(button).toBeVisible()
      await button.click()

      /* The button reports its own state, so this waits on the CONDITION rather
         than on a duration. */
      await expect(button).toHaveAttribute('aria-pressed', 'true')
      await page.waitForLoadState('networkidle')

      await expect(page).toHaveScreenshot(`${lesson.slug}.png`, {
        fullPage: true,
        maxDiffPixelRatio: MAX_DIFF_RATIO,
        /* Animations are already off in the reduced-motion project; this is the
           belt to that braces, and costs nothing when they are. */
        animations: 'disabled',
      })
    })
  }

  test('selecting a lesson actually changes what is rendered', async ({ page }) => {
    /*
     * The PAIR, and without it the whole file is satisfied by three identical
     * screenshots of whatever loaded first. A baseline suite that captured the
     * same page three times would pass forever while proving nothing about the
     * two lessons it never displayed.
     */
    await page.goto('/#/canvas')
    await page.waitForLoadState('networkidle')
    await canvasReady(page)

    const first = page.getByRole('button', { name: 'Physics', exact: true })
    const second = page.getByRole('button', { name: 'Civics', exact: true })

    await first.click()
    await expect(first).toHaveAttribute('aria-pressed', 'true')
    const physics = await page.locator('main').innerText()

    await second.click()
    await expect(second).toHaveAttribute('aria-pressed', 'true')
    await expect(first).toHaveAttribute('aria-pressed', 'false')
    const civics = await page.locator('main').innerText()

    expect(
      civics,
      'Both lessons rendered identical text, so the screenshots above are ' +
        'three captures of one page.',
    ).not.toBe(physics)
  })
})

/**
 * P12-T5 — under reduced motion the simulation must HOLD STILL.
 *
 * WHY THIS EXISTS, MEASURED RATHER THAN SUPPOSED
 * ----------------------------------------------
 * The first CI run of the baselines above failed on `gas` and only on `gas`:
 * two captures of the SAME commit on the SAME runner differed by ~14,000
 * pixels, a ratio of 0.01 -- five times `MAX_DIFF_RATIO`. `bill` and `ml` wrote
 * their images on the first attempt and never disagreed.
 *
 * The differing pixels were confined to a single rectangle, x 106..694 by
 * y 375..821, and every pixel outside it was identical. That rectangle is the
 * simulation surface.
 *
 * Two hypotheses were tested and one was refuted by measurement:
 *
 *   REFUTED  the lazy 3D scene had not finished loading, so one attempt caught
 *            the Suspense fallback. Both crops are fully rendered scenes --
 *            161 and 163 unique grey levels, means 30.0 and 30.2, standard
 *            deviations 27.0 and 27.1. A caption on a flat panel does not look
 *            like that.
 *   STANDS   the scene is still animating despite `prefers-reduced-motion`.
 *
 * SO THIS IS NOT A TEST PROBLEM
 * -----------------------------
 * `usePrefersReducedMotion` gates both surfaces and `reducedMotion: 'reduce'`
 * is set on this project, so a reader who asked the system to stop moving
 * things is being ignored. That is an accessibility defect that happens to
 * surface as a flaky screenshot. Committing a `gas` baseline without fixing it
 * would bake a permanently red gate into the pipeline and teach the next person
 * to regenerate baselines without looking -- the exact failure `visual-review.md`
 * is written to prevent.
 *
 * WAITING ON FRAMES, NOT ON THE CLOCK
 * -----------------------------------
 * The gap between the two captures is a number of ANIMATION FRAMES. A frame is
 * the unit the thing under test actually advances in, and it is why this file
 * carries no `waitForTimeout`: a duration would be a race dressed up as a
 * measurement.
 */
async function passFrames(page: Page, count: number): Promise<void> {
  for (let i = 0; i < count; i += 1) {
    await page.evaluate(() => new Promise<void>((r) => requestAnimationFrame(() => r())))
  }
}

/** The drawn surface of the gas lesson, whichever renderer produced it. */
function surfaceOf(page: Page) {
  return page.locator('main canvas, main svg[role="img"]').first()
}

async function openPhysics(page: Page): Promise<void> {
  await page.goto('/#/canvas')
  await page.waitForLoadState('networkidle')
  await canvasReady(page)
  const button = page.getByRole('button', { name: 'Physics', exact: true })
  await button.click()
  await expect(button).toHaveAttribute('aria-pressed', 'true')
  await page.waitForLoadState('networkidle')
}

test.describe('reduced motion holds the simulation still', () => {
  test('the gas surface is identical across frames', async ({ page }) => {
    await openPhysics(page)
    const surface = surfaceOf(page)
    await expect(surface).toBeVisible()

    /* Asserted BEFORE the pixels, because "the picture moved" has two causes
       that look identical from a screenshot: a loop that ignores `still`, and
       a `still` that never became true. This says which. */
    const media = await page.evaluate(
      () => window.matchMedia('(prefers-reduced-motion: reduce)').matches,
    )
    expect(media, 'The project sets reducedMotion: reduce but the page disagrees.').toBe(true)
    await expect(surface).toHaveAttribute('data-still', 'true')

    const before = await surface.screenshot()
    await passFrames(page, 30)
    const after = await surface.screenshot()

    expect(
      after.equals(before),
      'The simulation surface changed across 30 animation frames while ' +
        'prefers-reduced-motion is set. A reader who asked the system to stop ' +
        'moving things is being ignored, and every screenshot baseline of this ' +
        'lesson is unreproducible.',
    ).toBe(true)
  })

  test('and it DOES move when motion is allowed', async ({ browser, baseURL }) => {
    /*
     * The PAIR. "Identical across frames" is satisfied completely by a surface
     * that renders nothing, by a locator that matches an empty element, and by
     * a screenshot helper that returns the same buffer twice. Without this half
     * the test above proves only that something did not change, which is also
     * what a broken measurement looks like.
     */
    const context = await browser.newContext({ reducedMotion: 'no-preference', baseURL })
    const page = await context.newPage()
    try {
      await openPhysics(page)
      const surface = surfaceOf(page)
      await expect(surface).toBeVisible()

      const before = await surface.screenshot()
      await passFrames(page, 30)
      const after = await surface.screenshot()

      expect(
        after.equals(before),
        'The surface did not change over 30 frames with motion allowed, so ' +
          'the stillness test above is measuring nothing.',
      ).toBe(false)
    } finally {
      await context.close()
    }
  })
})
